### ISSUE TITLE
yarn build error on node_module of agGrid

### ISSUE THREAD

**Issue by alfdesign** [ag-grid/ag-grid#3344]
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```
Hi, i have this error when i try to build the my project with Angular 4.3.2, 

_view the image:_
https://user-images.githubusercontent.com/23096645/63960733-7430cc80-ca8f-11e9-971e-6ec337b8d28a.jpg

_or in the text version:_
**$ yarn build
yarn run v1.17.3
$ yarn run webpack:prod
$ yarn run cleanup && yarn run webpack:prod:main && yarn run clean-www
$ rimraf target/{aot,www}
$ yarn run webpack -- --config webpack/webpack.prod.js --progress --profile
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js --config webpack/webpack.prod.js --progress --profile
Starting compilation using the angular compiler.
(node:14208) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
Angular compilation done, starting webpack bundling.
Error: Error at C:/Users/alfonso.spinelli/sicma.plus.client/node_modules/ag-grid-community/dist/lib/widgets/agPanel.d.ts:18:23: Type expected.
Error at C:/Users/alfonso.spinelli/sicma.plus.client/node_modules/ag-grid-community/dist/lib/widgets/agPanel.d.ts:18:30: Identifier expected.
Error at C:/Users/alfonso.spinelli/sicma.plus.client/node_modules/ag-grid-community/dist/lib/widgets/agPanel.d.ts:18:30: A parameter initializer is only allowed in a functi
on or constructor implementation.
Error at C:/Users/alfonso.spinelli/sicma.plus.client/node_modules/ag-grid-community/dist/lib/widgets/agPanel.d.ts:18:47: ';' expected.
Error at C:/Users/alfonso.spinelli/sicma.plus.client/node_modules/ag-grid-community/dist/lib/widgets/agPanel.d.ts:19:29: Type expected.
Error at C:/Users/alfonso.spinelli/sicma.plus.client/node_modules/ag-grid-community/dist/lib/widgets/agPanel.d.ts:19:36: Identifier expected.
Error at C:/Users/alfonso.spinelli/sicma.plus.client/node_modules/ag-grid-community/dist/lib/widgets/agPanel.d.ts:19:36: A parameter initializer is only allowed in a functi
on or constructor implementation.
Error at C:/Users/alfonso.spinelli/sicma.plus.client/node_modules/ag-grid-community/dist/lib/widgets/agPanel.d.ts:19:60: ';' expected.
Error at C:/Users/alfonso.spinelli/sicma.plus.client/node_modules/ag-grid-community/dist/lib/widgets/agDialog.d.ts:31:29: Type expected.
Error at C:/Users/alfonso.spinelli/sicma.plus.client/node_modules/ag-grid-community/dist/lib/widgets/agDialog.d.ts:31:36: Identifier expected.
Error at C:/Users/alfonso.spinelli/sicma.plus.client/node_modules/ag-grid-community/dist/lib/widgets/agDialog.d.ts:31:36: A parameter initializer is only allowed in a funct
ion or constructor implementation.
Error at C:/Users/alfonso.spinelli/sicma.plus.client/node_modules/ag-grid-community/dist/lib/widgets/agDialog.d.ts:31:60: ';' expected.
Error at C:/Users/alfonso.spinelli/sicma.plus.client/node_modules/ag-grid-community/dist/lib/widgets/agDialog.d.ts:35:29: Type expected.
Error at C:/Users/alfonso.spinelli/sicma.plus.client/node_modules/ag-grid-community/dist/lib/widgets/agDialog.d.ts:35:36: Identifier expected.
Error at C:/Users/alfonso.spinelli/sicma.plus.client/node_modules/ag-grid-community/dist/lib/widgets/agDialog.d.ts:35:36: A parameter initializer is only allowed in a funct
ion or constructor implementation.
Error at C:/Users/alfonso.spinelli/sicma.plus.client/node_modules/ag-grid-community/dist/lib/widgets/agDialog.d.ts:35:50: ';' expected.
Error at C:/Users/alfonso.spinelli/sicma.plus.client/node_modules/ag-grid-community/dist/lib/widgets/agDialog.d.ts:55:22: Type expected.
Error at C:/Users/alfonso.spinelli/sicma.plus.client/node_modules/ag-grid-community/dist/lib/widgets/agDialog.d.ts:55:29: Identifier expected.
Error at C:/Users/alfonso.spinelli/sicma.plus.client/node_modules/ag-grid-community/dist/lib/widgets/agDialog.d.ts:55:29: A parameter initializer is only allowed in a funct
ion or constructor implementation.
Error at C:/Users/alfonso.spinelli/sicma.plus.client/node_modules/ag-grid-community/dist/lib/widgets/agDialog.d.ts:55:58: ';' expected.
    at new UserError (C:\Users\alfonso.spinelli\sicma.plus.client\node_modules\@angular\tsc-wrapped\src\tsc.js:27:28)
    at check (C:\Users\alfonso.spinelli\sicma.plus.client\node_modules\@angular\tsc-wrapped\src\tsc.js:93:15)
    at Tsc.typeCheck (C:\Users\alfonso.spinelli\sicma.plus.client\node_modules\@angular\tsc-wrapped\src\tsc.js:173:9)
    at C:\Users\alfonso.spinelli\sicma.plus.client\node_modules\@angular\tsc-wrapped\src\main.js:122:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.**



I have already tried to "exclude" node_modules in tsconfig.json
and also tried in webpack.prod but i don't resolve my problem.... any idea? help me...

**Comment by alfdesign** [comment]
in the file agPanel.d.ts, the error is bad import, how to resolve this problem? -->

declare const AgPanel_base: {
    new (...args: any[]): {
        [x: string]: any;
      -->  popupService: import("./popupService").PopupService;
      -->  gridOptionsWrapper: import("../gridOptionsWrapper").GridOptionsWrapper;
        renderComponent?(): void;
        config: any;
...

**Comment by davis4acca** [comment]
Hi,

Can you provide a reproducible scenario using one of our examples or your source code in a plunker and we will investigate?

Accepted reproducible scenarios are
- A description of the **detailed** steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Actual behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible
***

Note that this issue is getting closed, but you are welcomed to create a new issue if you can provide us with a reproducible scenario

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.
