### ISSUE TITLE
Charting - Plotting x axis with column set showRowGroup = true throws exceptions when viewportRowModel used

### ISSUE THREAD

**Issue by mattspeller** [ag-grid/ag-grid#3348]
**I'm submitting a ...**  (check one with "x")
[X] bug report

Current behaviour: Regression. Chart does not render with a dimension column with showRowGroup set to true.

Expected behaviour: Previous version 21.1.0 rendered the graph as expected. Data is flat as server renderered so there is no tree to walk for group values when creating label text.

**Providing a Reproducible Scenario**
https://next.plnkr.co/edit/LzANafYOgyQJL5co

TypeError: Cannot read property 'key' of undefined
    at ChartDatasource.webpackJsonp../node_modules/ag-grid-enterprise/dist/lib/chartAdaptor/chartComp/chartDatasource.js.ChartDatasource.getGroupLabels (\source\node_modules\ag-grid-enterprise\dist\lib\chartAdaptor\chartComp\chartDatasource.js:191:1)
    at \source\node_modules\ag-grid-enterprise\dist\lib\chartAdaptor\chartComp\chartDatasource.js:66:1
    at Array.forEach (<anonymous>)
    at _loop_1 (\source\node_modules\ag-grid-enterprise\dist\lib\chartAdaptor\chartComp\chartDatasource.js:56:1)
    at ChartDatasource.webpackJsonp../node_modules/ag-grid-enterprise/dist/lib/chartAdaptor/chartComp/chartDatasource.js.ChartDatasource.extractRowsFromGridRowModel (\source\node_modules\ag-grid-enterprise\dist\lib\chartAdaptor\chartComp\chartDatasource.js:120:1)
    at ChartDatasource.webpackJsonp../node_modules/ag-grid-enterprise/dist/lib/chartAdaptor/chartComp/chartDatasource.js.ChartDatasource.getData (\source\node_modules\ag-grid-enterprise\dist\lib\chartAdaptor\chartComp\chartDatasource.js:35:1)
    at ChartModel.webpackJsonp../node_modules/ag-grid-enterprise/dist/lib/chartAdaptor/chartComp/chartModel.js.ChartModel.updateData (\source\node_modules\ag-grid-enterprise\dist\lib\chartAdaptor\chartComp\chartModel.js:70:1)
    at ChartController.webpackJsonp../node_modules/ag-grid-enterprise/dist/lib/chartAdaptor/chartComp/chartController.js.ChartController.updateForMenuChange (\source\node_modules\ag-grid-enterprise\dist\lib\chartAdaptor\chartComp\chartController.js:67:1)
    at \source\node_modules\ag-grid-enterprise\dist\lib\chartAdaptor\chartComp\menu\data\chartDataPanel.js:79:1
    at \source\node_modules\ag-grid-community\dist\lib\eventService.js:133:1
    at Array.forEach (<anonymous>)
    at Function../node_modules/ag-grid-community/dist/lib/utils/general.js.Utils.forEachSnapshotFirst (\source\node_modules\ag-grid-community\dist\lib\utils\general.js:1374:1)
    at EventService../node_modules/ag-grid-community/dist/lib/eventService.js.EventService.dispatchToListeners (\source\node_modules\ag-grid-community\dist\lib\eventService.js:128:1)
    at EventService../node_modules/ag-grid-community/dist/lib/eventService.js.EventService.dispatchEvent (\source\node_modules\ag-grid-community\dist\lib\eventService.js:105:1)
    at AgRadioButton../node_modules/ag-grid-community/dist/lib/context/beanStub.js.BeanStub.dispatchEvent (\source\node_modules\ag-grid-community\dist\lib\context\beanStub.js:75:1)
    at AgRadioButton../node_modules/ag-grid-community/dist/lib/widgets/agCheckbox.js.AgCheckbox.setSelected (\source\node_modules\ag-grid-community\dist\lib\widgets\agCheckbox.js:121:1)
    at AgRadioButton../node_modules/ag-grid-community/dist/lib/widgets/agCheckbox.js.AgCheckbox.setValue (\source\node_modules\ag-grid-community\dist\lib\widgets\agCheckbox.js:138:1)
    at AgRadioButton../node_modules/ag-grid-community/dist/lib/widgets/agRadioButton.js.AgRadioButton.toggle (\source\node_modules\ag-grid-community\dist\lib\widgets\agRadioButton.js:37:1)
    at AgRadioButton../node_modules/ag-grid-community/dist/lib/widgets/agCheckbox.js.AgCheckbox.onClick (\source\node_modules\ag-grid-community\dist\lib\widgets\agCheckbox.js:77:1)
    at HTMLDivElement.<anonymous> (\source\node_modules\ag-grid-community\dist\lib\widgets\agCheckbox.js:63:1)

**Please tell us about your environment:**
see plunkr for simple recreate.

* **ag-Grid version:** 21.2.0
* **Browser:** chrome
* **Language:** react / JS

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by davis4acca** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:

AG-3308  Charts - Add support for viewportRowModel
