### ISSUE TITLE
Focus out not triggering second time when we click inside the gird

### ISSUE THREAD

**Issue by ajithanageswari** [ag-grid/ag-grid#3415]
app.component.ts

onFocusOut(): void {
   this.params.api.stopEditing();
}
app.component.html

<input #container triggers="" type="text" class="form-control" 
[(ngModel)]="dateValue"
(focusOut)="onFocusOut()">

Implemented the above code in first focus and blur its working properly but in second focus and focusing out thorws an error
core.js:1673 ERROR DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
    at Function.push../node_modules/ag-grid-community/dist/lib/utils.js.Utils.clearElement (http://10.17.30.45:8090/vendor.js:166796:16)
    at CellComp.push../node_modules/ag-grid-community/dist/lib/rendering/cellComp.js.CellComp.stopEditing (http://10.17.30.45:8090/vendor.js:155768:23)
    at CellComp.push../node_modules/ag-grid-community/dist/lib/rendering/cellComp.js.CellComp.stopRowOrCellEdit (http://10.17.30.45:8090/vendor.js:155726:18)
    at CellComp.push../node_modules/ag-grid-community/dist/lib/rendering/cellComp.js.CellComp.onCellFocused (http://10.17.30.45:8090/vendor.js:155716:18)
    at http://10.17.30.45:8090/vendor.js:140930:17
    at Array.forEach (<anonymous>)
    at Function.push../node_modules/ag-grid-community/dist/lib/utils.js.Utils.forEachSnapshotFirst (http://10.17.30.45:8090/vendor.js:167457:23)
    at EventService.push../node_modules/ag-grid-community/dist/lib/eventService.js.EventService.dispatchToListeners (http://10.17.30.45:8090/vendor.js:140925:19)
    at EventService.push../node_modules/ag-grid-community/dist/lib/eventService.js.EventService.dispatchEvent (http://10.17.30.45:8090/vendor.js:140902:14)
    at FocusedCellController.push../node_modules/ag-grid-community/dist/lib/focusedCellController.js.FocusedCellController.onCellFocused (http://10.17.30.45:8090/vendor.js:144877:27)

**Comment by davis4acca** [comment]
Hi,

Unfortunately we can't tell what your issue is given your description. 

This ticket is going to be flagged as managed_by_the_comunnity, this means that ag-grid staff is not going to be actively looking into it, and it will get closed if inactive for more than one month, the community is welcome to help with this question/support issue

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

**Comment by diwakarsingh** [comment]
+1
Facing the same issue

**Comment by georghendrik** [comment]
I'm also experiencing this quite interesting bug. **There's a workaround at the bottom of this comment.**

The origin of the `DOMException` is `Utils.clearElement`:
```
Utils.clearElement = function (el) {
    while (el && el.firstChild) {
        el.removeChild(el.firstChild);
    }
};
```

The call to `el.removeElement(el.firstChild)` triggers the `DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?`.

So why is this interesting? 
- The DOMException does not occur if you step through the code: if you add breakpoints to every statement of `Utils.clearElement`, and step through them one-by-one, everything works just fine.
- Without those breakpoints, the DOMException triggers and shows `el.removeElement` was called with `null`. That should be impossible, since the while loop verifies `el.firstChild` to be truthy
- Adding a conditional breakpoint on `el.removeChild` with `el.firstChild == null` does not trigger that breakpoint, but does trigger the `DOMException` instead.

It appears that somehow, while `Utils.clearElement` is running, something else is altering the DOM, removing `el.firstChild` from `el` immediately after it was verified to exist. That explanation does not fit the Javascript single-threaded execution model, so I'm very curious to hear alternative explanations.

**Workaround**
This describes how to patch ag-grid's `Utils.clearElement` at runtime to clear a HTMLElement atomically using innerHTML.

Create a file patchAgGrid.ts (assuming you're using Angular / TypeScript):

```
import { Utils } from '@ag-grid-community/all-modules';

export function patchAgGrid() {
    // Prevent DOMException after editing cells.
    Utils.clearElement = function (el: HTMLElement) {
        el.innerHTML = "";
    }
}
```

Call `patchAgGrid()` when starting your app, e.g. in app.component.ts if you're using Angular.

If you consider applying this workaround, please be sure to verify that patching third party code in this way is an acceptable engineering practice in your organisation, and that clearing elements using innerHTML works for your targeted browsers - there is likely a reason that Ag-Grid uses `el.removeChild` instead of `el.innerHTML`.
