### ISSUE TITLE
Angular 6 and 7 apps fail production build with Ag Grid 

### ISSUE THREAD

**Issue by jasonlenthe** [ag-grid/ag-grid#3759]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

Production builds fail for Angular 6 and 7 projects with Ag Grid 23.0.02, but works fine with Ag Grid 22.1.1.  The error is

```
ERROR in ./node_modules/ag-grid-angular/fesm5/ag-grid-angular.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (/home/jlenthe/code/bug/grid-test-angular6/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:242:35)
    at checkNodeForDecorators (/home/jlenthe/code/bug/grid-test-angular6/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:67:21)
    at visitNodes (/home/jlenthe/code/bug/grid-test-angular6/node_modules/typescript/lib/typescript.js:14809:30)
    at Object.forEachChild (/home/jlenthe/code/bug/grid-test-angular6/node_modules/typescript/lib/typescript.js:15033:24)
    at checkNodeForDecorators (/home/jlenthe/code/bug/grid-test-angular6/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:58:31)
    at visitNode (/home/jlenthe/code/bug/grid-test-angular6/node_modules/typescript/lib/typescript.js:14800:24)
    at Object.forEachChild (/home/jlenthe/code/bug/grid-test-angular6/node_modules/typescript/lib/typescript.js:14928:21)
    at checkNodeForDecorators (/home/jlenthe/code/bug/grid-test-angular6/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:58:31)
    at visitNode (/home/jlenthe/code/bug/grid-test-angular6/node_modules/typescript/lib/typescript.js:14800:24)
    at Object.forEachChild (/home/jlenthe/code/bug/grid-test-angular6/node_modules/typescript/lib/typescript.js:14985:24)
    at checkNodeForDecorators (/home/jlenthe/code/bug/grid-test-angular6/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:58:31)
    at visitNode (/home/jlenthe/code/bug/grid-test-angular6/node_modules/typescript/lib/typescript.js:14800:24)
    at Object.forEachChild (/home/jlenthe/code/bug/grid-test-angular6/node_modules/typescript/lib/typescript.js:14996:24)
    at checkNodeForDecorators (/home/jlenthe/code/bug/grid-test-angular6/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:58:31)
    at visitNode (/home/jlenthe/code/bug/grid-test-angular6/node_modules/typescript/lib/typescript.js:14800:24)
    at Object.forEachChild (/home/jlenthe/code/bug/grid-test-angular6/node_modules/typescript/lib/typescript.js:14893:21)
```

Here are the detailed steps to reproduce:

1) Create an Angular 6 or 7 project with Ag Grid (steps below show 6 but 7 is done similarly)
```bash
$ mkdir old_cli
$ cd old_cli/
$ npm init
$ npm install @angular/cli@6
$ cd ..
$ old_cli/node_modules/@angular/cli/bin/ng new grid-test-angular6
$ cd grid-test-angular6/
$ npm install ag-grid-community ag-grid-angular --save
```

2) Add a grid to the app.component
  a) Add `AgGridModule.withComponents([])` to the Angular imports in in app.module.ts
  b) Add an `<ag-grid-angular></ag-grid-angular>` component in app.component

3) Run `$ ng build --prod` and observe the error.  `ng serve` works fine.

**Expected behavior**
We expected this combination of package versions (Angular 6 or 7 and Ag Grid 23.0.02) to work because the Ag Grid change log entry for [AG-3802](https://www.ag-grid.com/ag-grid-changelog/) says that 

> Angular 6+ is now the minimum supported version Angular.

**Please tell us about your environment:**

* **ag-Grid version:** 23.0.2
* **O/S version:** Ubuntu 18.04.4 LTS
* **npm version:** 6.9.0

For Angular 6:
* **@angular/core version:** 6.1.0
* **@angular/cli version:** 6.2.9
* **Language:** TypeScript 2.9.2

For Angular 7:
* **@angular/core version:** 7.2.0
* **@angular/cli version:** 7.3.10
* **Language:** TypeScript 3.2.2

**Comment by seanlandsman** [comment]
Hi - this has been resolved with issue AG-4040 (https://www.ag-grid.com/ag-grid-pipeline/). 

We should be issuing a patch soon to resolve this issue.

thanks

**Comment by jasonlenthe** [comment]
> Hi - this has been resolved with issue AG-4040 (https://www.ag-grid.com/ag-grid-pipeline/).
> 
> We should be issuing a patch soon to resolve this issue.
> 

Great to hear.  Thank you!

**Comment by seanlandsman** [comment]
23.0.3 has just been released - let me know if this solves this issue for you 

thanks
