### ISSUE TITLE
nuxt3: SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by razbakov** [ag-grid/ag-grid#4848]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**How to reproduce:**
- Take [vue3 example](https://codesandbox.io/s/ag-grid-vue-3-example-bvwik?file=/src/main.js)
- Add `nuxt3`
- Move `app.vue` to root folder
- Change serve script to `nuxi dev`

**Environment:**
- nuxt3: ^3.0.0-27338323.1e98259
- node: 14.18.2
- ag-grid-community: 26.2.1
- ag-grid-vue3: 26.2.0

**Expected behavior**
No errors

**Current behavior**
Error:

```
(node:34515) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
~/Code/ag-grid-vue3-example/node_modules/ag-grid-vue3/lib/AgGridVue.js:20
import { h } from 'vue';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (~/Code/ag-grid-vue3-example/node_modules/ag-grid-vue3/main.js:5:10)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
[vite dev] Error loading external "~/Code/ag-grid-vue3-example/node_modules/ag-grid-vue3/main.js".
  at file://./.nuxt/dist/server/server.mjs:1972:297  
  at async __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:2082:3)
m.default is not a function
  at file://./.nuxt/dist/server/server.mjs:10:126  
  at processTicksAndRejections (internal/process/task_queues.js:95:5)  
  at async renderToString (file://./node_modules/vue-bundle-renderer/dist/index.mjs:248:19)  
  at async renderMiddleware (file://./.nuxt/nitro/index.mjs:191:20)  
  at async handle (file://./node_modules/h3/dist/index.mjs:601:19)
m.default is not a function
  at file://./.nuxt/dist/server/server.mjs:10:126  
  at processTicksAndRejections (internal/process/task_queues.js:95:5)  
  at async renderToString (file://./node_modules/vue-bundle-renderer/dist/index.mjs:248:19)  
  at async renderMiddleware (file://./.nuxt/nitro/index.mjs:191:20)  
  at async handle (file://./node_modules/h3/dist/index.mjs:601:19)
```

**Comment by razbakov** [comment]
I guess same problem as in https://github.com/ag-grid/ag-grid/issues/4694

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by icedjello** [comment]
Hi, 

Thanks for raising this but I've been unable to recreate this case on my end based on the instructions provided. Would you be able to provide me with a repo-link or zip file that illustrates this issue? 

Thanks,

**Comment by loremru** [comment]
> Hi,
> 
> Thanks for raising this but I've been unable to recreate this case on my end based on the instructions provided. Would you be able to provide me with a repo-link or zip file that illustrates this issue?
> 
> Thanks,

Hi, ag-grid doesn't work in ssr mode of nuxt 3, but in spa it's ok.

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Comment by razbakov** [comment]
@makinggoodsoftware any updates?

**Comment by makinggoodsoftware** [comment]
Hi,

Apologies for the long wait, our devs expent some time looking at nuxt3 and while there seem to be some issues since it is still in Beta:

https://v3.nuxtjs.org/community/roadmap 

It has been decided to wait and revisit once they release a stable version

Does this make sense? Would it be an option to open a new ticket when the first stable version is out so we can have a look?
