### ISSUE TITLE
[Enterprise] [MasterDetail] [React]

### ISSUE THREAD

**Issue by przemo098** [ag-grid/ag-grid#4921]
Currently I'm trying to find out how can I create or get access to Zendesk

AgGrid master detail copied from your official docs doesn't work
https://www.ag-grid.com/react-data-grid/master-detail/

```
ag-grid-enterprise.cjs.js:51528 Uncaught TypeError: Cannot add property refreshStrategy, object is not extensible
    at DetailCellRendererCtrl.ensureValidRefreshStrategy (ag-grid-enterprise.cjs.js:51528:1)
    at DetailCellRendererCtrl.init (ag-grid-enterprise.cjs.js:51493:1)
    at detailCellRenderer.js:58:1
    at invokePassiveEffectCreate (react-dom.development.js:23487:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at flushPassiveEffectsImpl (react-dom.development.js:23574:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
```

https://github.com/przemo098/ag-grid-master-detail-error
```
npm install
npm start
```

**Comment by joemacstevens** [comment]
im also facing this issue

**Comment by ctrlemo** [comment]
Also ran into this issue.

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Also, please contact us at info@ag-grid.com where they will be able to assist you with your access to Zendesk

Thanks

**Comment by coder36** [comment]
Have the same issue.  v27.0.x is unusable for master/detail

**Comment by kiril-matev** [comment]
Hello!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6446 [Regression] When using master/detail with custom cell renderer in the detail grid, expanding a row throws an exception**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by kiril-matev** [comment]
Hello @przemo098,

Please email info@ag-grid.com with your AG Grid license key to get access to Zendesk support.

**Comment by johnscillieri** [comment]
I see that this is scheduled for next release, any idea when that will happen?

**Comment by jackdh** [comment]
+1

**Comment by kiril-matev** [comment]
The next version of AG Grid which will address this issue is currently scheduled for release before March 18th.

**Comment by manuTro** [comment]
Hi, I still have this error. Anyone in the same situation?
