### ISSUE TITLE
Cannot read properties of null (reading 'forEach') in case of multiple filters

### ISSUE THREAD

**Issue by sohaibex** [ag-grid/ag-grid#5138]
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'

AG Grid EE
Angular 10

i have multiple filters with in all columns when i filter with diffrents columns and i do an action that required refreshing data 
i got this error i had the remove the multiplefilters and make just agSetColumnFilter and applyMiniFilterWhileTyping to work.

My filters:

```

filter: 'agMultiColumnFilter', 
filterParams: 
{ filters: 
[
{ filter: 'agTextColumnFilter', },  
{
                filter: 'agSetColumnFilter',
                filterParams: 
                {
                  applyMiniFilterWhileTyping: true,
                },
 },
], 
},

```

    core.js:4197 
    ERROR TypeError: Cannot read properties of null (reading 'forEach')
    at FilterService.push.f7ga.FilterService.setAllChildrenCountGridGrouping (ag-grid-community.cjs.js:43021:1)
    at FilterService.push.f7ga.FilterService.setAllChildrenCount (ag-grid-community.cjs.js:43036:1)
    at filterCallback (ag-grid-community.cjs.js:42973:1)
    at defaultFilterCallback (ag-grid-community.cjs.js:43003:61)
    at ChangedPath.push.f7ga.ChangedPath.depthFirstSearchEverything (ag-grid-community.cjs.js:17373:1)
    at ChangedPath.push.f7ga.ChangedPath.forEachChangedNodeDepthFirst (ag-grid-community.cjs.js:17386:1)
    at FilterService.push.f7ga.FilterService.filterNodes (ag-grid-community.cjs.js:43004:1)
    at FilterService.push.f7ga.FilterService.filter (ag-grid-community.cjs.js:42949:1)
    at FilterStage.push.f7ga.FilterStage.execute (ag-grid-community.cjs.js:42415:1)
    at ClientSideRowModel.push.f7ga.ClientSideRowModel.doFilter (ag-grid-community.cjs.js:42208:1)

**Comment by makinggoodsoftware** [comment]
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Comment by 0wlcat** [comment]
@makinggoodsoftware Greeting

Faced same issue on my current project. [CustomFilterComponent](https://www.ag-grid.com/react-data-grid/component-filter/) was made by another team and I don't know what exactly cause the error but it's crushes the whole app.

They was trying to "clear  filters without reflecting" using `filter.setModel(null)`.

```
Uncaught TypeError: Cannot read properties of null (reading 'forEach')
    at FilterService.setAllChildrenCountGridGrouping (ag-grid-community.cjs.js:48022:1)
    at FilterService.setAllChildrenCount (ag-grid-community.cjs.js:48037:1)
    at filterCallback (ag-grid-community.cjs.js:47970:1)
    at defaultFilterCallback (ag-grid-community.cjs.js:48004:62)
    at ChangedPath.depthFirstSearchEverything (ag-grid-community.cjs.js:19641:1)
    at ChangedPath.forEachChangedNodeDepthFirst (ag-grid-community.cjs.js:19654:1)
    at FilterService.filterNodes (ag-grid-community.cjs.js:48005:1)
    at FilterService.filter (ag-grid-community.cjs.js:47945:1)
    at FilterStage.execute (ag-grid-community.cjs.js:47439:1)
    at ClientSideRowModel.doFilter (ag-grid-community.cjs.js:47178:1)
```
