### ISSUE TITLE
React DOM error warning

### ISSUE THREAD

**Issue by khaladj** [ag-grid/ag-grid#5200]
I've upgraded and then this is happening. 

react-dom.development.js:68 Warning: Invalid aria prop `aria-description` on <div> tag. For details, see https://reactjs.org/link/invalid-aria-props
    at div
    at HeaderCellComp (http://localhost:3000/static/js/bundle.js:139005:25)
    at div
    at HeaderRowComp (http://localhost:3000/static/js/bundle.js:139516:36)
    at div
    at div
    at HeaderRowContainerComp (http://localhost:3000/static/js/bundle.js:139687:20)
    at div
    at GridHeaderComp (http://localhost:3000/static/js/bundle.js:138901:20)
    at div
    at GridBodyComp (http://localhost:3000/static/js/bundle.js:138421:20)
    at TabGuardCompRef (http://localhost:3000/static/js/bundle.js:140456:24)
    at div
    at div
    at GridComp (http://localhost:3000/static/js/bundle.js:138657:20)
    at div
    at AgGridReactUi (http://localhost:3000/static/js/bundle.js:137027:24)
    at AgGridReact (http://localhost:3000/static/js/bundle.js:136357:43)
    at div
    at div
    at div
    at EventManger (http://localhost:3000/static/js/bundle.js:16670:76)
    at Routes (http://localhost:3000/static/js/bundle.js:230169:5)
    at div
    at App (http://localhost:3000/static/js/bundle.js:764:82)
    at Router (http://localhost:3000/static/js/bundle.js:230102:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:228912:5)
    at PersistGate (http://localhost:3000/static/js/bundle.js:234837:5)
    at Provider (http://localhost:3000/static/js/bundle.js:226093:20)
printWarning @ react-dom.development.js:68
error @ react-dom.development.js:44
warnInvalidARIAProps @ react-dom.development.js:3351
validateProperties @ react-dom.development.js:3363
validatePropertiesInDevelopment @ react-dom.development.js:8800
setInitialProperties @ react-dom.development.js:9072
finalizeInitialChildren @ react-dom.development.js:10225
completeWork @ react-dom.development.js:19346
completeUnitOfWork @ react-dom.development.js:22650
performUnitOfWork @ react-dom.development.js:22622
workLoopSync @ react-dom.development.js:22548
renderRootSync @ react-dom.development.js:22514
performSyncWorkOnRoot @ react-dom.development.js:22131
(anonymous) @ react-dom.development.js:11379
unstable_runWithPriority @ scheduler.development.js:465
runWithPriority$1 @ react-dom.development.js:11325
flushSyncCallbackQueueImpl @ react-dom.development.js:11374
flushSyncCallbackQueue @ react-dom.development.js:11362
flushPassiveEffectsImpl @ react-dom.development.js:23434
unstable_runWithPriority @ scheduler.development.js:465
runWithPriority$1 @ react-dom.development.js:11325
flushPassiveEffects @ react-dom.development.js:23267
(anonymous) @ react-dom.development.js:23148
workLoop @ scheduler.development.js:415
flushWork @ scheduler.development.js:389
performWorkUntilDeadline @ scheduler.development.js:155

**Comment by seanlandsman** [comment]
Hi - this is an issue with react - fixed in version 18: https://github.com/facebook/react/issues/21035

thanks

**Comment by shmoeaz** [comment]
@seanlandsman, I know this is a closed issue, however, is there a way to resolve this issue without upgrading React? 
We are using React 17.0.2 and AG Grid install indicates that it support ^17.0.0, and I would expect that this means without errors. We are evaluating AG Grid and I really like what I see, but we can have a javascript error being thrown all the time.

**Comment by StephenCooper** [comment]
Unfortunately not as this is a bug with React trying to validate aria props, which as you know they have now fixed.

As this is a React issue, see: https://github.com/facebook/react/issues/21035, we are not able to prevent the error on those specific versions.
