### ISSUE TITLE
aria-description error with upgrading from 27.2=>27.3

### ISSUE THREAD

**Issue by vishnu4** [ag-grid/ag-grid#5211]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Simple scenario.  I was using ag-grid-community/ag-grid-react  versions ^27.2.x and i recently upgraded to ^27.3.x.  Now when i run my jest tests, i get errors that:

```
console.error
      Warning: Invalid aria prop `aria-description` on <div> tag. For details, see https://reactjs.org/link/invalid-aria-props
          at div
          at HeaderCellComp (C:\Code\COBRAGit2\COBRA5\cobraspa\node_modules\ag-grid-react\lib\reactUi\header\headerCellComp.js:29:27)
          at div
          at HeaderRowComp (C:\Code\COBRAGit2\COBRA5\cobraspa\node_modules\ag-grid-react\lib\reactUi\header\headerRowComp.js:29:38)
          at div
          at div
          at HeaderRowContainerComp (C:\Code\COBRAGit2\COBRA5\cobraspa\node_modules\ag-grid-react\lib\reactUi\header\headerRowContainerComp.js:21:22)
          at div
          at GridHeaderComp (C:\Code\COBRAGit2\COBRA5\cobraspa\node_modules\ag-grid-react\lib\reactUi\header\gridHeaderComp.js:21:22)
          at div
          at GridBodyComp (C:\Code\COBRAGit2\COBRA5\cobraspa\node_modules\ag-grid-react\lib\reactUi\gridBodyComp.js:23:22)
          at TabGuardCompRef (C:\Code\COBRAGit2\COBRA5\cobraspa\node_modules\ag-grid-react\lib\reactUi\tabGuardComp.js:16:26)
          at div
          at div
          at GridComp (C:\Code\COBRAGit2\COBRA5\cobraspa\node_modules\ag-grid-react\lib\reactUi\gridComp.js:23:22)
          at div
          at AgGridReactUi (C:\Code\COBRAGit2\COBRA5\cobraspa\node_modules\ag-grid-react\lib\reactUi\agGridReactUi.js:52:28)
          at AgGridReact (C:\Code\COBRAGit2\COBRA5\cobraspa\node_modules\ag-grid-react\lib\agGridReact.js:41:47)

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at warnInvalidARIAProps (node_modules/react-dom/cjs/react-dom.development.js:3371:7)
      at validateProperties (node_modules/react-dom/cjs/react-dom.development.js:3383:3)
      at validatePropertiesInDevelopment (node_modules/react-dom/cjs/react-dom.development.js:8763:5)
      at setInitialProperties (node_modules/react-dom/cjs/react-dom.development.js:9041:5)
      at finalizeInitialChildren (node_modules/react-dom/cjs/react-dom.development.js:10201:3)
      at completeWork (node_modules/react-dom/cjs/react-dom.development.js:19470:17)
```

it looks like from the snapshot that this version upgrade changed aria-label => aria-description, and my setup doesn't like this change.  Any workarounds, or should this change be reverted?

I'm using react-scripts 5.0.1, typescript 4.4.4, and react 17.0.2

**Comment by seanlandsman** [comment]
Hi - this is an issue with react - fixed in version 18: https://github.com/facebook/react/issues/21035

thanks
