### ISSUE TITLE
aria-description error

### ISSUE THREAD

**Issue by ldeveber** [ag-grid/ag-grid#5258]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

zendesk is down, I can't log in :(
<img width="279" alt="Screen Shot 2022-06-08 at 1 50 12 PM" src="https://user-images.githubusercontent.com/4457752/172683843-296e8e8f-715f-4b94-af4d-39d0cf4adc6e.png">

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker
upgrade 27.2 -> 27.3

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state. Current behaviour. Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

```
react-dom.development.js?61bb:67 Warning: Invalid aria prop `aria-description` on <div> tag. For details, see https://reactjs.org/link/invalid-aria-props
    at div
    at HeaderCellComp (webpack-internal:///./node_modules/@ag-grid-community/react/lib/reactUi/header/headerCellComp.js:18:33)
    at div
    at HeaderRowComp (webpack-internal:///./node_modules/@ag-grid-community/react/lib/reactUi/header/headerRowComp.js:22:44)
    at div
    at HeaderRowContainerComp (webpack-internal:///./node_modules/@ag-grid-community/react/lib/reactUi/header/headerRowContainerComp.js:21:49)
    at div
    at GridHeaderComp (webpack-internal:///./node_modules/@ag-grid-community/react/lib/reactUi/header/gridHeaderComp.js:21:49)
    at div
    at GridBodyComp (webpack-internal:///./node_modules/@ag-grid-community/react/lib/reactUi/gridBodyComp.js:23:83)
    at TabGuardCompRef (webpack-internal:///./node_modules/@ag-grid-community/react/lib/reactUi/tabGuardComp.js:16:13)
    at div
    at div
    at GridComp (webpack-internal:///./node_modules/@ag-grid-community/react/lib/reactUi/gridComp.js:22:21)
    at div
    at AgGridReactUi (webpack-internal:///./node_modules/@ag-grid-community/react/lib/reactUi/agGridReactUi.js:27:9)
    at AgGridReact (webpack-internal:///./node_modules/@ag-grid-community/react/lib/agGridReact.js:16:9)
    at div
    at GridBase (webpack-internal:///./src/components/grid/GridBase.js:124:86)
    at I18nextWithTranslation (webpack-internal:///./node_modules/react-i18next/dist/es/withTranslation.js:27:31)
    at ConnectFunction (webpack-internal:///./node_modules/react-redux/es/components/connectAdvanced.js:233:68)
    at div
    at DuplicatesGrid (webpack-internal:///./src/pages/Dedupe/grid/DuplicatesGrid.js:74:86)
    at I18nextWithTranslation (webpack-internal:///./node_modules/react-i18next/dist/es/withTranslation.js:27:31)
    at ConnectFunction (webpack-internal:///./node_modules/react-redux/es/components/connectAdvanced.js:233:68)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:28:19741)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:28:19741)
    at main
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:28:19741)
    at MergeManagement (webpack-internal:///./src/pages/Dedupe/MergeManagement.js:75:87)
    at ScenarioLoader (webpack-internal:///./src/containers/ScenarioLoader.js:32:23)
    at Routes (webpack-internal:///./node_modules/react-router/index.js:271:5)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:28:19741)
    at ScenarioLayout (webpack-internal:///./src/containers/ScenarioLayout.js:87:84)
    at Routes (webpack-internal:///./node_modules/react-router/index.js:271:5)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:28:19741)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:28:19741)
    at DefaultLayout (webpack-internal:///./src/containers/DefaultLayout.js:69:87)
    at Routes (webpack-internal:///./node_modules/react-router/index.js:271:5)
    at DTApp (webpack-internal:///./src/DTApp.js:43:73)
    at Routes (webpack-internal:///./node_modules/react-router/index.js:271:5)
    at App (webpack-internal:///./src/App.js:30:77)
    at Router (webpack-internal:///./node_modules/react-router/index.js:205:15)
    at BrowserRouter (webpack-internal:///./node_modules/react-router-dom/index.js:115:5)
    at Provider (webpack-internal:///./node_modules/react-redux/es/components/Provider.js:15:20)
    at Suspense
    at ErrorBoundary (webpack-internal:///./src/services/ErrorBoundary.js:51:86)
    at Fe (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:28:17300)
printWarning @ react-dom.development.js?61bb:67
error @ react-dom.development.js?61bb:43
warnInvalidARIAProps @ react-dom.development.js?61bb:3371
validateProperties @ react-dom.development.js?61bb:3383
validatePropertiesInDevelopment @ react-dom.development.js?61bb:8763
setInitialProperties @ react-dom.development.js?61bb:9041
finalizeInitialChildren @ react-dom.development.js?61bb:10201
completeWork @ react-dom.development.js?61bb:19470
completeUnitOfWork @ react-dom.development.js?61bb:22812
performUnitOfWork @ react-dom.development.js?61bb:22787
workLoopSync @ react-dom.development.js?61bb:22707
renderRootSync @ react-dom.development.js?61bb:22670
performSyncWorkOnRoot @ react-dom.development.js?61bb:22293
eval @ react-dom.development.js?61bb:11327
unstable_runWithPriority @ scheduler.development.js?3069:468
runWithPriority$1 @ react-dom.development.js?61bb:11276
flushSyncCallbackQueueImpl @ react-dom.development.js?61bb:11322
flushSyncCallbackQueue @ react-dom.development.js?61bb:11309
scheduleUpdateOnFiber @ react-dom.development.js?61bb:21893
enqueueSetState @ react-dom.development.js?61bb:12467
Component.setState @ react.development.js?72d0:365
onSuccess @ GridBase.js?04ae:96
eval @ DuplicatesGrid.js?786f:43
Promise.then (async)
eval @ DuplicatesGrid.js?786f:40
eval @ GridBase.js?04ae:101
oneTimeSetupCallback @ GridBase.js?04ae:183
onSuccess @ GridBase.js?04ae:191
eval @ DuplicatesGrid.js?786f:66
Promise.then (async)
eval @ DuplicatesGrid.js?786f:59
getRows @ GridBase.js?04ae:209
eval @ storeUtils.js?4693:60
setTimeout (async)
StoreUtils.loadFromDatasource @ storeUtils.js?4693:54
PartialStoreBlock.loadFromDatasource @ partialStoreBlock.js?f727:249
RowNodeBlock.load @ rowNodeBlock.js?d060:35
RowNodeBlockLoader.performCheckBlocksToLoad @ rowNodeBlockLoader.js?2550:99
RowNodeBlockLoader.checkBlockToLoad @ rowNodeBlockLoader.js?2550:80
RowNodeBlockLoader.addBlock @ rowNodeBlockLoader.js?2550:59
PartialStore.createBlock @ partialStore.js?d805:566
blockNotFoundFunc @ partialStore.js?d805:494
PartialStore.findBlockAndExecute @ partialStore.js?d805:298
PartialStore.getRowUsingDisplayIndex @ partialStore.js?d805:497
ServerSideRowModel.getRow @ serverSideRowModel.js?a49b:235
PaginationProxy.getRow @ paginationProxy.js?a89e:104
RowRenderer.createOrUpdateRowCtrl @ rowRenderer.js?b3de:805
eval @ rowRenderer.js?b3de:704
RowRenderer.redraw @ rowRenderer.js?b3de:703
RowRenderer.redrawAfterModelUpdate @ rowRenderer.js?b3de:377
RowRenderer.onPageLoaded @ rowRenderer.js?b3de:250
eval @ eventService.js?cd37:104
processEventListeners @ eventService.js?cd37:99
EventService.dispatchToListeners @ eventService.js?cd37:109
EventService.dispatchEvent @ eventService.js?cd37:88
PaginationProxy.onModelUpdated @ paginationProxy.js?a89e:67
eval @ eventService.js?cd37:104
processEventListeners @ eventService.js?cd37:99
EventService.dispatchToListeners @ eventService.js?cd37:109
EventService.dispatchEvent @ eventService.js?cd37:88
ServerSideRowModel.dispatchModelUpdated @ serverSideRowModel.js?a49b:200
ServerSideRowModel.resetRootStore @ serverSideRowModel.js?a49b:154
ServerSideRowModel.setDatasource @ serverSideRowModel.js?a49b:79
GridApi.setServerSideDatasource @ gridApi.js?e180:180
eval @ GridBase.js?04ae:188
GridOptionsWrapper.globalEventHandler @ gridOptionsWrapper.js?c5bb:1451
eval @ eventService.js?cd37:114
VanillaFrameworkOverrides.dispatchEvent @ vanillaFrameworkOverrides.js?e3be:33
eval @ eventService.js?cd37:114
eval @ eventService.js?cd37:150
EventService.flushAsyncQueue @ eventService.js?cd37:150
setTimeout (async)
EventService.dispatchAsync @ eventService.js?cd37:134
eval @ eventService.js?cd37:114
EventService.dispatchToListeners @ eventService.js?cd37:112
EventService.dispatchEvent @ eventService.js?cd37:87
GridOptionsWrapper.getScrollbarWidth @ gridOptionsWrapper.js?c5bb:1227
GridOptionsWrapper.init @ gridOptionsWrapper.js?c5bb:172
eval @ context.js?7fcf:182
Context.callLifeCycleMethodsOnBean @ context.js?7fcf:182
eval @ context.js?7fcf:165
Context.callLifeCycleMethods @ context.js?7fcf:165
Context.wireBeans @ context.js?7fcf:44
Context @ context.js?7fcf:22
GridCoreCreator.create @ grid.js?9b05:161
componentDidMount @ agGridReactUi.js?781d:100
commitLifeCycles @ react-dom.development.js?61bb:20663
commitLayoutEffects @ react-dom.development.js?61bb:23426
callCallback @ react-dom.development.js?61bb:3945
invokeGuardedCallbackDev @ react-dom.development.js?61bb:3994
invokeGuardedCallback @ react-dom.development.js?61bb:4056
commitRootImpl @ react-dom.development.js?61bb:23151
unstable_runWithPriority @ scheduler.development.js?3069:468
runWithPriority$1 @ react-dom.development.js?61bb:11276
commitRoot @ react-dom.development.js?61bb:22990
performSyncWorkOnRoot @ react-dom.development.js?61bb:22329
eval @ react-dom.development.js?61bb:11327
unstable_runWithPriority @ scheduler.development.js?3069:468
runWithPriority$1 @ react-dom.development.js?61bb:11276
flushSyncCallbackQueueImpl @ react-dom.development.js?61bb:11322
flushSyncCallbackQueue @ react-dom.development.js?61bb:11309
scheduleUpdateOnFiber @ react-dom.development.js?61bb:21893
dispatchAction @ react-dom.development.js?61bb:16139
eval @ index.js?2512:2
call @ index.js?2512:2
z @ index.js?2512:4
A @ index.js?2512:5
eval @ index.js?0a87:383
finishTask @ PreviewRecordsBtn.js?d445:43
onTaskComplete @ AsyncTaskButton.js?8c27:42
onMessage @ AsyncTaskProgressModal.js?7222:67
eval @ client.js?7e10:100
eval @ stomp.js?48c1:296
EventTarget.dispatchEvent @ eventtarget.js?97a2:51
eval @ main.js?486c:282
SockJS._transportMessage @ main.js?486c:280
EventEmitter.emit @ emitter.js?ada0:50
WebSocketTransport.ws.onmessage @ websocket.js?397f:35
Show 83 more frames
```

**Expected behavior**

No errors in bumping a minor version (dependency updates should not ever require a minor version)

**Please tell us about your environment:**

* **AG Grid version:** X.X.X

27.3

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
React 17... we can't upgrade because of other libraries

**Comment by gportela85** [comment]
This is a React issue, see: https://github.com/facebook/react/issues/21035

This has also been reported here by: 

https://github.com/ag-grid/ag-grid/issues/5211
https://github.com/ag-grid/ag-grid/issues/5200

**Comment by skaempfer** [comment]
Opening this up because I ran into accessibility validation issues with the use of the aria-description as well.

When running accessibility checks with [Accessibility Insights](https://accessibilityinsights.io/) on a page with AG Grid and sortable columns (which use `aria-description` for communicating usage information for the sorting functions) I receive the following validation error: **Invalid ARIA attribute name: aria-description**

This is because `aria-description` was first introduced in the [WAI-ARIA 1.3 specification](https://w3c.github.io/aria/) which is still in DRAFT status. The current non-draft version is still [WAI-ARIA 1.1](https://www.w3.org/TR/wai-aria-1.1/)

Imo we are in a kind of grey spoy here. On one hand `aria-description` gains more and more support afaik, on the other hand manual and automated validations for pages using aria-description might rightfully declare its use as an error since its not really standard compliant. This can become a serious issues when accessibility level standards like WCAG are applied to a website.

Did you take this into consideration when switching to `aria-description`?
Further, is there any way to work around this when using sortable columns or any other AG Grid function that makes use of `aria-description` attribute?

**Comment by AinTunez** [comment]
@skaempfer 

Here's the band-aid fix I implemented in TypeScript.

```ts
const suppressConsoleError = (shouldBeHidden: (message: string) => boolean) => {
    const err = console.error
    console.error = (message?: any, ...optionalParams: any[]) => {
        if (typeof message === "string" && shouldBeHidden(message)) {
            return
        }
        err(message, ...optionalParams)
    }
}

suppressConsoleError(m => m.startsWith("Warning: Invalid aria prop"))
```

**Comment by robrichardson27** [comment]
I'm running into the same violation @skaempfer mentions (Invalid ARIA attribute name: aria-description) with our automated a11y tests - that use axe-core 4.4.2.

To me it seems a little too early to start using `aria-description` as it may not be supported by all screen readers.

Is there a way to work around this at all?

**Comment by tahoon-ms** [comment]
Validation errors aside, what is the purpose of using aria-description here? WAI-ARIA 1.3 is still in draft state, not all browsers support it, let alone screen readers. If this has an important purpose, consider using aria-describedby, which has robust support.

**Comment by MatrixSpock** [comment]
Hello, i'm running into the same error here. Any update or solution to this yet?

**Comment by sindhuraN** [comment]
Did we find any resolution here. I am also running into the same issue when running an accessibility check with Accessbility insights tool.  Is there a workaround for this. Agdrid version - 28.2.1 . React version V18

**Comment by kiril-matev** [comment]
Hi all,

The original issue reported here was in AG Grid v27.3 and React 17 - an exception was shown in console:
react-dom.development.js?61bb:67 Warning: Invalid aria prop `aria-description` on <div> tag.

As mentioned before, this is due to a known issue with React Dev mode:
https://github.com/facebook/react/issues/21035

This exception won't occur in prod mode. This issue is fixed in React v18.

Please either use AG Grid v27.2 (instead of AG Grid 27.3) with React 17, or upgrade to React 18 to resolve this issue.
