### ISSUE TITLE
Row dissappears when clicked on custom checkbox

### ISSUE THREAD

**Issue by caveofjulian** [ag-grid/ag-grid#5931]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- First time a row with custom checkbox renderer is clicked, it disappears. When you click the checkbox next to it a strange blue line appears. This only happened after an upgrade of Vue.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
First time a row with custom checkbox renderer is clicked, it disappears. When you click the checkbox next to it a strange blue line appears. It seems to be the row that belongs in the empty white space. An exception (From Vue) occurs in the console: 
```
Cannot read properties of null (reading 'nextSibling')
```
Followed by an exception from Ag-Grid:
```
G Grid: cannot get grid to draw rows when it is in the middle of drawing rows. Your code probably called a grid API method while the grid was in the render stage. To overcome this, put the API call into a timeout, e.g. instead of api.refreshView(), call setTimeout(function() { api.refreshView(); }, 0). To see what part of your code that caused the refresh check this stacktrace.
    at RowRenderer.getLockOnRefresh (ag-grid-community.cjs.js:2731:192)
    at RowRenderer.redrawAfterModelUpdate (ag-grid-community.cjs.js:2719:99)
    at RowRenderer.onPageLoaded (ag-grid-community.cjs.js:2702:21)
    at eval (ag-grid-community.cjs.js:177:1733)
    at Set.forEach (<anonymous>)
    at processEventListeners (ag-grid-community.cjs.js:177:1633)
    at EventService.dispatchToListeners (ag-grid-community.cjs.js:177:1824)
    at EventService.dispatchEvent (ag-grid-community.cjs.js:177:1276)
    at PaginationProxy.onModelUpdated (ag-grid-community.cjs.js:4020:2318)
    at eval (ag-grid-community.cjs.js:177:1733)
```
*Nowhere in the code refreshView is called

**Expected behavior**
Checkbox is checked and no rows dissappear.

**Please tell us about your environment:**
Windows 10, Visual Studio Code, Chrome.

* **AG Grid version:** 26.1.0

```
"dependencies": {
    "@codemirror/lang-javascript": "^6.1.1",
    "@codemirror/lang-xml": "^6.0.1",
    "@codemirror/theme-one-dark": "^6.1.0",
    "@coreui/coreui": "^4.2.4",
    "@coreui/coreui-pro": "^4.4.2",
    "@coreui/icons": "^2.1.0",
    "@coreui/icons-vue": "^2.0.0-beta.0",
    "@coreui/utils": "^1.3.1",
    "@coreui/vue-pro": "^4.0.1",
    "@fullcalendar/core": "^5.10.1",
    "@fullcalendar/daygrid": "^5.10.1",
    "@fullcalendar/interaction": "^5.10.1",
    "@fullcalendar/vue3": "^5.10.1",
    "@meforma/vue-toaster": "^1.3.0",
    "@vue/cli-plugin-babel": "^5.0.8",
    "ag-grid-community": "26.1.0",
    "ag-grid-vue3": "26.1.2",
    "axios": "^0.21.4",
    "codemirror": "^6.0.1",
    "core-js": "^3.19.1",
    "css-loader": "^6.5.1",
    "keycloak-js": "^17.0.1",
    "moment": "^2.29.1",
    "postcss": "^8.3.11",
    "postcss-loader": "^6.2.0",
    "vue": "3.2.45",
    "vue-class-component": "^8.0.0-rc.1",
    "vue-codemirror": "^6.1.1",
    "vue-router": "4.0.12",
    "vue-select": "^4.0.0-beta.6",
    "vuex": "4.0.2",
    "node-polyfill-webpack-plugin": "^2.0.1",
    "vue3-treeview": "^0.4.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.5",
    "@babel/eslint-parser": "^7.19.1",
    "@popperjs/core": "^2.11.6",
    "@vue/cli-plugin-babel": "^5.0.8",
    "@vue/cli-plugin-eslint": "^5.0.8",
    "@vue/cli-plugin-router": "^5.0.8",
    "@vue/cli-plugin-vuex": "^5.0.8",
    "@vue/cli-service": "^5.0.8",
    "@vue/compiler-sfc": "3.2.21",
    "@vue/eslint-config-prettier": "^7.0.0",
    "eslint": "^8.30.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^6.1.1",
    "eslint-plugin-standard": "^4.1.0",
    "eslint-plugin-vue": "^9.8.0",
    "less": "^4.1.3",
    "less-loader": "^11.1.0",
    "prettier": "^2.8.1",
    "sass": "^1.57.1",
    "sass-loader": "^13.2.0"
  }, 
```

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by StephenCooper** [comment]
Hi @caveofjulian,

Could you please provide a reproduction so that we can re-create the issue and then debug it? Without this we will not be able to work out what the issue is.
