### ISSUE TITLE
ERROR on Ag-grid-angular on Storybook

### ISSUE THREAD

**Issue by maalej** [ag-grid/ag-grid#6393]
**I'm submitting a
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[X] support request => see 'Requesting Community Support'
```
**Requesting Community Support**
Hello, I am creating a story for ag-grid-angular on Storybook, the data renders well, however I have 2 errors in the console:
```
core.mjs:7753 ERROR TypeError: (defs || []).map is not a function
    at ColumnFactory.recursivelyCreateColumns (ag-grid-community.auto.esm.js:2750:1)
    at ColumnFactory.createColumnTree (ag-grid-community.auto.esm.js:2621:1)
    at ColumnModel.createColumnsFromColumnDefs (ag-grid-community.auto.esm.js:4806:1)
    at ColumnModel.setColumnDefs (ag-grid-community.auto.esm.js:4766:1)
    at GridApi.setColumnDefs (ag-grid-community.auto.esm.js:20361:1)
    at ComponentUtil.processOnChange (ag-grid-community.auto.esm.js:3547:1)
    at AgGridAngular.ngOnChanges (ag-grid-angular.js:1047:1)
    at AgGridAngular.rememberChangeHistoryAndInvokeOnChangesHook (core.mjs:1515:1)
    at callHook (core.mjs:2568:1)
    at callHooks (core.mjs:2527:1)
```

**Providing a Reproducible Scenario**
here's is my component.ts code
```
import { Component } from '@angular/core';
import { ColDef } from 'ag-grid-community';

@Component({
  selector: 'virtual-table',
  templateUrl: './virtualTable.component.html',
  styleUrls: ['./virtualTable.component.css']
})
export default class VirtualTableComponent {

  columnDefs: ColDef[] = [
    { field: 'make' },
    { field: 'model' },
    { field: 'price' }
  ];

  rowData = [
    { make: 'Toyota', model: 'Celica', price: 35000 },
    { make: 'Ford', model: 'Mondeo', price: 32000 },
    { make: 'Porsche', model: 'Boxster', price: 72000 }
  ];
}

```
my component.html code
```
<ag-grid-angular
  style="width: 500px; height: 200px;"
  class="ag-theme-alpine"
  [rowData]="rowData"
  [columnDefs]="columnDefs">
</ag-grid-angular>

```
And this is my story code:
```
import { Story, Meta } from '@storybook/angular/types-6-0';
import VirtualTableComponent from '../components/VirtualTable/virtualTable.component';
import { moduleMetadata } from '@storybook/angular';
import { AgGridModule } from 'ag-grid-angular';

export default {
  title: 'Widget/VirtualTableComponent',
  component: VirtualTableComponent,
  argTypes: {
  },
  decorators: [
    moduleMetadata({
      imports: [AgGridModule],
    })
  ]
} as Meta;

const Template: Story<VirtualTableComponent> = (args: VirtualTableComponent) => ({
  props: args,
});

export const Default = Template.bind({});
  Default.args = {
};
```

**Current behavior**
Everything renders well, however I have 2 weird errors in the console.
![image](https://user-images.githubusercontent.com/2788104/228225108-f51e243d-c262-4ca7-b53b-35330f65c3cd.png)

**Expected behavior**
no errors in the console

**Please tell us about your environment:**
Debian 10

* **AG Grid version:** 29.2.0

* **Browser:**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by maalej** [comment]
at a certain time, the columnDefs array was passed as a string
