### ISSUE TITLE
Warning: Invalid aria prop `aria-description` on <div> tag

### ISSUE THREAD

**Issue by kaiyoma** [ag-grid/ag-grid#6684]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Current behavior**
If you write a Jest/Vitest unit test that tests a component that renders an ag-grid table, you'll see this error output:

```
Warning: Invalid aria prop `aria-description` on <div> tag. For details, see https://reactjs.org/link/invalid-aria-props
    at div
    at HeaderCellComp (C:\Users\kgetz\Work\event-viewer\node_modules\.pnpm\@ag-grid-community+react@29.2.0_66iw4qxthhgdmzuveprybaacf4\node_modules\@ag-grid-community\react\lib\reactUi\header\headerCellComp.js:30:33)
    at div
    at HeaderRowComp (C:\Users\kgetz\Work\event-viewer\node_modules\.pnpm\@ag-grid-community+react@29.2.0_66iw4qxthhgdmzuveprybaacf4\node_modules\@ag-grid-community\react\lib\reactUi\header\headerRowComp.js:34:44)
    at div
    at div
    at HeaderRowContainerComp (C:\Users\kgetz\Work\event-viewer\node_modules\.pnpm\@ag-grid-community+react@29.2.0_66iw4qxthhgdmzuveprybaacf4\node_modules\@ag-grid-community\react\lib\reactUi\header\headerRowContainerComp.js:33:49)
    at div
    at GridHeaderComp (C:\Users\kgetz\Work\event-viewer\node_modules\.pnpm\@ag-grid-community+react@29.2.0_66iw4qxthhgdmzuveprybaacf4\node_modules\@ag-grid-community\react\lib\reactUi\header\gridHeaderComp.js:33:49)
    at div
    at GridBodyComp (C:\Users\kgetz\Work\event-viewer\node_modules\.pnpm\@ag-grid-community+react@29.2.0_66iw4qxthhgdmzuveprybaacf4\node_modules\@ag-grid-community\react\lib\reactUi\gridBodyComp.js:35:83)
    at TabGuardCompRef (C:\Users\kgetz\Work\event-viewer\node_modules\.pnpm\@ag-grid-community+react@29.2.0_66iw4qxthhgdmzuveprybaacf4\node_modules\@ag-grid-community\react\lib\reactUi\tabGuardComp.js:28:13)
    at div
    at div
    at GridComp (C:\Users\kgetz\Work\event-viewer\node_modules\.pnpm\@ag-grid-community+react@29.2.0_66iw4qxthhgdmzuveprybaacf4\node_modules\@ag-grid-community\react\lib\reactUi\gridComp.js:34:21)
    at div
    at AgGridReactUi (C:\Users\kgetz\Work\event-viewer\node_modules\.pnpm\@ag-grid-community+react@29.2.0_66iw4qxthhgdmzuveprybaacf4\node_modules\@ag-grid-community\react\lib\reactUi\agGridReactUi.js:39:9)
    at AgGridReact (C:\Users\kgetz\Work\event-viewer\node_modules\.pnpm\@ag-grid-community+react@29.2.0_66iw4qxthhgdmzuveprybaacf4\node_modules\@ag-grid-community\react\lib\agGridReact.js:29:9)
```

**Expected behavior**
No error.

**Please tell us about your environment:**

* **AG Grid version:** 29.2.0

* **Browser:** N/A

* **Language:** all

**Comment by kiril-matev** [comment]
Hi all,

This isn't an issue with AG Grid.

This is caused by a known issue with React 17.x and earlier. Specifically, this is an issue with React Dev mode and this exception won't occur in prod mode.

Please see this issue logged for React here:
https://github.com/facebook/react/issues/21035

Here's the actual change in React 18 to fix this:
https://github.com/facebook/react/pull/22142

In order to fix this issue, please upgrade to React 18 or later.
