### ISSUE TITLE
'agGroupColumnFilter' filter type in ag-Grid encountering an error when attempting to reset the column state,

### ISSUE THREAD

**Issue by Ahmadraza444** [ag-grid/ag-grid#6805]
Plnkr example: https://plnkr.co/edit/EjBvM3Jf1oBNz4P2?open=app%2Fapp.component.ts

core.mjs:7621 ERROR TypeError: Cannot read properties of null (reading 'getColId')
    at e.setGroupValue (ag-grid-community.cjs.min.js:207:134472)
    at eval (ag-grid-community.cjs.min.js:357:34317)
    at Array.forEach (<anonymous>)
    at eval (ag-grid-community.cjs.min.js:357:34162)
    at Array.forEach (<anonymous>)
    at t.pullDownGroupDataForHideOpenParents (ag-grid-community.cjs.min.js:357:34102)
    at eval (ag-grid-community.cjs.min.js:357:31155)
    at e.depthFirstSearchEverything (ag-grid-community.cjs.min.js:319:719)
    at e.depthFirstSearchEverything (ag-grid-community.cjs.min.js:319:655)
    at e.forEachChangedNodeDepthFirst (ag-grid-community.cjs.min.js:319:891)

**Comment by kiril-matev** [comment]
Hello @Ahmadraza444,

Thank for reporting this.

This issue is no longer reproducible with AG Grid v30.0.2. I've updated the version of AG Grid in your example and confirmed this issue is no longer there:
1. Open
https://plnkr.co/edit/LAXCH7OVERJAoJ1I?open=app%2Fapp.component.ts
2. Open console
3. Group by COUNTRY
4. Click button above grid
Actual & Expected: No exception in console

Please note the console warning - AG Grid: Group Column Filter does not work with the colDef property "filterValueGetter". This property will be ignored.

You can't use the agGroupColumnFilter with a filterValueGetter - it's one or the other and the agGroupColumnFilter takes precedence.

In any case, update the AG Grid version to v30 or later to resolve this.

**Comment by Ahmadraza444** [comment]
Hi @kiril-matev,

Thanks a lot for quick response.
