### ISSUE TITLE
ag api render bug

### ISSUE THREAD

**Issue by Alkimay** [ag-grid/ag-grid#6810]
**Hey i am getting this a lot recently. maybe its bad use of api in my code but i get white screens. even if there is an issue i dont want to get white screen, stop this draw from happening maybe, thanks or enveloup yourself with setTimout.... 
Thanks**

ag-grid-community.auto.esm.js:34155 Uncaught Error: AG Grid: cannot get grid to draw rows when it is in the middle of drawing rows. Your code probably called a grid API method while the grid was in the render stage. To overcome this, put the API call into a timeout, e.g. instead of api.redrawRows(), call setTimeout(function() { api.redrawRows(); }, 0). To see what part of your code that caused the refresh check this stacktrace.
    at RowRenderer.getLockOnRefresh (ag-grid-community.auto.esm.js:34155:1)
    at RowRenderer.redrawAfterModelUpdate (ag-grid-community.auto.esm.js:34103:1)
    at RowRenderer.onPageLoaded (ag-grid-community.auto.esm.js:34008:1)
    at ag-grid-community.auto.esm.js:1183:1
    at Set.forEach (<anonymous>)
    at processEventListeners (ag-grid-community.auto.esm.js:1178:1)
    at EventService.dispatchToListeners (ag-grid-community.auto.esm.js:1189:1)
    at EventService.dispatchEvent (ag-grid-community.auto.esm.js:1160:1)
    at PaginationProxy.onModelUpdated (ag-grid-community.auto.esm.js:35590:1)
    at ag-grid-community.auto.esm.js:1183:1
    at Set.forEach (<anonymous>)
    at processEventListeners (ag-grid-community.auto.esm.js:1178:1)
    at EventService.dispatchToListeners (ag-grid-community.auto.esm.js:1189:1)
    at EventService.dispatchEvent (ag-grid-community.auto.esm.js:1160:1)
    at ClientSideRowModel.refreshModel (ag-grid-community.auto.esm.js:46025:1)
    at ClientSideRowModel.commonUpdateRowData (ag-grid-community.auto.esm.js:46487:1)
    at ClientSideRowModel.updateRowData (ag-grid-community.auto.esm.js:46464:1)
    at ImmutableService.setRowData (ag-grid-community.auto.esm.js:47087:1)
    at GridApi.setRowData (ag-grid-community.auto.esm.js:19279:1)
    at GridApi.__setProperty (ag-grid-community.auto.esm.js:19111:1)
    at ag-grid-community.auto.esm.js:4059:1
    at Array.forEach (<anonymous>)
    at ComponentUtil.processOnChange (ag-grid-community.auto.esm.js:4056:1)
    at agGridReactUi.js:115:1
    at agGridReactUi.js:101:1
    at agGridReactUi.js:112:1
    at invokePassiveEffectCreate (react-dom.development.js:23487:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at flushPassiveEffectsImpl (react-dom.development.js:23574:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushPassiveEffects (react-dom.development.js:23447:1)
    at performSyncWorkOnRoot (react-dom.development.js:22269:1)
    at react-dom.development.js:11327:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js:11309:1)
    at scheduleUpdateOnFiber (react-dom.development.js:21893:1)
    at dispatchAction (react-dom.development.js:16139:1)
    at rowContainerComp.js:35:1
    at agFlushSync (utils.js:48:1)
    at updateRowCtrlsOrdered (rowContainerComp.js:34:1)
    at Object.setRowCtrls (rowContainerComp.js:60:1)
    at RowContainerCtrl.onDisplayedRowsChanged (ag-grid-community.auto.esm.js:27344:1)
    at ag-grid-community.auto.esm.js:27203:1
    at ag-grid-community.auto.esm.js:1183:1
    at Set.forEach (<anonymous>)

**Comment by kiril-matev** [comment]
Hi @Alkimay,

Thanks for reporting this.

We cannot investigate this with the input you provided.

Please follow the bug report template and provide a sample to reproduce this issue.

Looking forward to your response.
