### ISSUE TITLE
[React] AGGrid not working with React Suspense

### ISSUE THREAD

**Issue by nnnnoel** [ag-grid/ag-grid#6826]
**I'm submitting a ...**  (check one with "x")

- [x] bug report => see 'Providing a Reproducible Scenario'
- [ ] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
- [ ] support request => see 'Requesting Community Support'

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.
![image](https://github.com/ag-grid/ag-grid/assets/67718949/d46a459c-cb73-4b89-a5c8-13c45f3904fc)
1. enter suspend mode
2. ag grid rendered
3. re-enter suspend mode cause of another actions
4. ag grid dead & not working any actions
Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

not working

**Expected behavior**

works fine

**Please tell us about your environment:**

nextjs 13.4.4
react 18.2.0

* **AG Grid version:** 29.3.5

* **Browser:** all

* **Language:** all

**Comment by StephenCooper** [comment]
V30 contains fixes for Suspense so could you please try upgrading as a first step.

**Comment by nnnnoel** [comment]
```
- error /Users/noel/work/quotalab/quotabook-frontend/.yarn/cache/ag-grid-enterprise-npm-30.0.2-3430c47c11-57be285060.zip/node_modules/ag-grid-enterprise/dist/ag-grid-enterprise.auto.esm.js:6
import { PreConstruct, Bean, BeanStub, Autowired, RefSelector, PostConstruct, Component, ModuleNames, Optional, _, Events, ChangedPath, CsvExportModule, KeyCode, EventService, Column, ProvidedColumnGroup, AgMenuList, AgMenuItemComponent, AgCheckbox, CssClassApplier, DragSourceType, DragAndDropService, TouchListener, AutoScrollService, PreDestroy, VirtualList, NumberSequence, RowNode, ManagedFocusFeature, PositionableFeature, TabGuardComp, AgSelect, AgPromise, AgInputTextField, ModuleRegistry, ExcelFactoryMode, XmlFactory, BaseGridSerializingSession, RowType, ZipContainer, Downloader, BaseCreator, GridSerializer, CsvCreator, AgGroupComponent, AgAbstractField, AgRadioButton, AgToggleButton, AgAbstractLabel, AgSlider, DEFAULT_CHART_GROUPS, TabbedLayout, CHART_TOOLBAR_ALLOW_LIST, CHART_TOOL_PANEL_ALLOW_LIST, CHART_TOOL_PANEL_MENU_OPTIONS, AgPanel, CellRangeType, AgDialog, CellCtrl, SelectionHandleType, AgPickerField, Grid, ProvidedFilter, PopupComponent, RowNodeBlock, ServerSideTransactionResultStatus, RowNodeBlockLoader, GROUP_AUTO_COLUMN_ID, TextFilter, AllCommunityModules } from 'ag-grid-community';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:353:18)
    at wrapSafe (node:internal/modules/cjs/loader:1040:15)
    at Module._compile (node:internal/modules/cjs/loader:1076:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at require$$0.Module._extensions..js (/Users/noel/work/quotalab/quotabook-frontend/.pnp.cjs:31207:33)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at require$$0.Module._load (/Users/noel/work/quotalab/quotabook-frontend/.pnp.cjs:31044:14)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Hook.Module.require (/Users/noel/work/quotalab/quotabook-frontend/.yarn/unplugged/dd-trace-npm-3.8.0-9d1e37dbcf/node_modules/dd-trace/packages/dd-trace/src/ritm.js:73:33)
    at require (node:internal/modules/cjs/helpers:102:18)
    at ag-grid-enterprise (/Users/noel/work/quotalab/quotabook-frontend/.next/server/pages/investor/[my_institution_id]/fund/[fund_id]/distributions/create.js:1756:18)
    at __webpack_require__ (/Users/noel/work/quotalab/quotabook-frontend/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/shared/components/base/AgDataGrid/index.tsx:14:76)
    at __webpack_require__.a (/Users/noel/work/quotalab/quotabook-frontend/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./src/shared/components/base/AgDataGrid/index.tsx:1:21)
    at ./src/shared/components/base/AgDataGrid/index.tsx (/Users/noel/work/quotalab/quotabook-frontend/.next/server/pages/investor/[my_institution_id]/fund/[fund_id]/distributions/create.js:407:1)
    at __webpack_require__ (/Users/noel/work/quotalab/quotabook-frontend/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/investors/funds/containers/DistributionCreateOrEditPage/DistributionEditForm.tsx:19:92)
    at __webpack_require__.a (/Users/noel/work/quotalab/quotabook-frontend/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./src/investors/funds/containers/DistributionCreateOrEditPage/DistributionEditForm.tsx:1:21)
    at ./src/investors/funds/containers/DistributionCreateOrEditPage/DistributionEditForm.tsx (/Users/noel/work/quotalab/quotabook-frontend/.next/server/pages/investor/[my_institution_id]/fund/[fund_id]/distributions/create.js:187:1)
    at __webpack_require__ (/Users/noel/work/quotalab/quotabook-frontend/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/investors/funds/containers/DistributionCreateOrEditPage/index.tsx:11:79)
    at __webpack_require__.a (/Users/noel/work/quotalab/quotabook-frontend/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./src/investors/funds/containers/DistributionCreateOrEditPage/index.tsx:1:21)
    at ./src/investors/funds/containers/DistributionCreateOrEditPage/index.tsx (/Users/noel/work/quotalab/quotabook-frontend/.next/server/pages/investor/[my_institution_id]/fund/[fund_id]/distributions/create.js:209:1)
    at __webpack_require__ (/Users/noel/work/quotalab/quotabook-frontend/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/investor/[my_institution_id]/fund/[fund_id]/distributions/create/index.ts:8:113)
    at __webpack_require__.a (/Users/noel/work/quotalab/quotabook-frontend/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./pages/investor/[my_institution_id]/fund/[fund_id]/distributions/create/index.ts:1:21)
    at ./pages/investor/[my_institution_id]/fund/[fund_id]/distributions/create/index.ts (/Users/noel/work/quotalab/quotabook-frontend/.next/server/pages/investor/[my_institution_id]/fund/[fund_id]/distributions/create.js:22:1)
    at __webpack_require__ (/Users/noel/work/quotalab/quotabook-frontend/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./.yarn/__virtual__/next-virtual-256a2db119/0/cache/next-npm-13.4.4-eea4a310b2-d84686f3ca.zip/node_modules/next/dist/build/webpack/loaders/next-route-loader.js?page=%2Finvestor%2F%5Bmy_institution_id%5D%2Ffund%2F%5Bfund_id%5D%2Fdistributions%2Fcreate&absolutePagePath=.%2Fpages%2Finvestor%2F%5Bmy_institution_id%5D%2Ffund%2F%5Bfund_id%5D%2Fdistributions%2Fcreate%2Findex.ts&preferredRegion=!:6:134)
    at __webpack_require__.a (/Users/noel/work/quotalab/quotabook-frontend/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./.yarn/__virtual__/next-virtual-256a2db119/0/cache/next-npm-13.4.4-eea4a310b2-d84686f3ca.zip/node_modules/next/dist/build/webpack/loaders/next-route-loader.js?page=%2Finvestor%2F%5Bmy_institution_id%5D%2Ffund%2F%5Bfund_id%5D%2Fdistributions%2Fcreate&absolutePagePath=.%2Fpages%2Finvestor%2F%5Bmy_institution_id%5D%2Ffund%2F%5Bfund_id%5D%2Fdistributions%2Fcreate%2Findex.ts&preferredRegion=!:1:21)
    at ./.yarn/__virtual__/next-virtual-256a2db119/0/cache/next-npm-13.4.4-eea4a310b2-d84686f3ca.zip/node_modules/next/dist/build/webpack/loaders/next-route-loader.js?page=%2Finvestor%2F%5Bmy_institution_id%5D%2Ffund%2F%5Bfund_id%5D%2Fdistributions%2Fcreate&absolutePagePath=.%2Fpages%2Finvestor%2F%5Bmy_institution_id%5D%2Ffund%2F%5Bfund_id%5D%2Fdistributions%2Fcreate%2Findex.ts&preferredRegion=! (/Users/noel/work/quotalab/quotabook-frontend/.next/server/pages/investor/[my_institution_id]/fund/[fund_id]/distributions/create.js:33:1)
    at __webpack_require__ (/Users/noel/work/quotalab/quotabook-frontend/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/noel/work/quotalab/quotabook-frontend/.next/server/pages/investor/[my_institution_id]/fund/[fund_id]/distributions/create.js:2239:39)
    at /Users/noel/work/quotalab/quotabook-frontend/.next/server/pages/investor/[my_institution_id]/fund/[fund_id]/distributions/create.js:2240:28
    at Object.<anonymous> (/Users/noel/work/quotalab/quotabook-frontend/.next/server/pages/investor/[my_institution_id]/fund/[fund_id]/distributions/create.js:2243:3)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at require$$0.Module._extensions..js (/Users/noel/work/quotalab/quotabook-frontend/.pnp.cjs:31207:33)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at require$$0.Module._load (/Users/noel/work/quotalab/quotabook-frontend/.pnp.cjs:31044:14)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Hook.Module.require (/Users/noel/work/quotalab/quotabook-frontend/.yarn/unplugged/dd-trace-npm-3.8.0-9d1e37dbcf/node_modules/dd-trace/packages/dd-trace/src/ritm.js:73:33)
    at require (node:internal/modules/cjs/helpers:102:18)
    at requirePage (/Users/noel/work/quotalab/quotabook-frontend/.yarn/__virtual__/next-virtual-256a2db119/0/cache/next-npm-13.4.4-eea4a310b2-d84686f3ca.zip/node_modules/next/dist/server/require.js:156:12)
    at /Users/noel/work/quotalab/quotabook-frontend/.yarn/__virtual__/next-virtual-256a2db119/0/cache/next-npm-13.4.4-eea4a310b2-d84686f3ca.zip/node_modules/next/dist/server/load-components.js:68:84
```

**Comment by StephenCooper** [comment]
Please see https://github.com/ag-grid/ag-grid/issues/6789#issuecomment-1602155214

**Comment by nnnnoel** [comment]
@StephenCooper Thanks a lot. This issue has been resolved.
