### ISSUE TITLE
Redrawing fails in a test after upgrade from 30.1.0 to 30.2.0

### ISSUE THREAD

**Issue by air2** [ag-grid/ag-grid#7099]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
I have a github repo:
https://github.com/air2/ag-grid-angular-hello-world-us7mv6
Run `npm i`
then run `npm test`
The test fails

If reporting a bug make sure to state.

**Current behavior**
The test fails with the following error:

```
hrome Headless 119.0.6011.0 (Windows 10) BackupListComponent expect the correct backup data in the grid FAILED
        Error: AG Grid: cannot get grid to draw rows when it is in the middle of drawing rows. Your code probably called a grid API method while the grid was in the render stage. To overcome this, put the API call into a timeout, e.g. instead of api.redrawRows(), call setTimeout(function() { api.redrawRows(); }, 0). To see what part of your code that caused the refresh check this stacktrace.
            at RowRenderer.getLockOnRefresh (node_modules/@ag-grid-community/core/dist/esm/es6/rendering/rowRenderer.mjs:408:19)
            at RowRenderer.redrawAfterModelUpdate (node_modules/@ag-grid-community/core/dist/esm/es6/rendering/rowRenderer.mjs:352:14)
            at RowRenderer.listener [as onPageLoaded] (node_modules/@ag-grid-community/core/dist/esm/es6/rendering/rowRenderer.mjs:239:14)
            at forEach (node_modules/@ag-grid-community/core/dist/esm/es6/eventService.mjs:113:17)
            at Set.forEach (<anonymous>)
            at processEventListeners (node_modules/@ag-grid-community/core/dist/esm/es6/eventService.mjs:108:64)
            at EventService.dispatchToListeners (node_modules/@ag-grid-community/core/dist/esm/es6/eventService.mjs:119:13)
            at EventService.dispatchEvent (node_modules/@ag-grid-community/core/dist/esm/es6/eventService.mjs:90:14)
            at PaginationProxy.listener [as onModelUpdated] (node_modules/@ag-grid-community/core/dist/esm/es6/pagination/paginationProxy.mjs:51:27)
            at node_modules/@ag-grid-community/core/dist/esm/es6/eventService.mjs:113:17Chrome Headless 119.0.6011.0 (Windows 10): Executed 1 of 2 (1 FAILED) (0 secs / 0.08 secs)
Chrome Headless 119.0.6011.0 (Windows 10) BackupListComponent expect the correct backup data in the grid FAILED
        Error: AG Grid: cannot get grid to draw rows when it is in the middle of drawing rows. Your code probably called a grid API method while the grid was in the render stage. To overcome this, put the API call into a timeout, e.g. instead of api.redrawRows(), call setTimeout(function() { api.redrawRows(); }, 0). To see what part of your code that caused the refresh check this stacktrace.
            at RowRenderer.getLockOnRefresh (node_modules/@ag-grid-community/core/dist/esm/es6/rendering/rowRenderer.mjs:408:19)
            at RowRenderer.redrawAfterModelUpdate (node_modules/@ag-grid-community/core/dist/esm/es6/rendering/rowRenderer.mjs:352:14)
            at RowRenderer.listener [as onPageLoaded] (node_modules/@ag-grid-community/core/dist/esm/es6/rendering/rowRenderer.mjs:239:14)
            at forEach (node_modules/@ag-grid-community/core/dist/esm/es6/eventService.mjs:113:17)
            at Set.forEach (<anonymous>)
            at processEventListeners (node_modules/@ag-grid-community/core/dist/esm/es6/eventService.mjs:108:64)
            at EventService.dispatchToListeners (node_modules/@ag-grid-community/core/dist/esm/es6/eventService.mjs:119:13)
            at EventService.dispatchEvent (node_modules/@ag-grid-community/core/dist/esm/es6/eventService.mjs:90:14)
```
If you remove the line 
```jasmine.clock().tick(300)```
in `list.component.ts:48`  the error is gone. However this error was not happening in previous versions

**Expected behavior**
The test succeeds as it did in 30.1.0

**Please tell us about your environment:**
Windows 11, Visual code.

* **AG Grid version:** 30.2.0

**Comment by StephenCooper** [comment]
Hi @air2,

I have taken a look at your repo and it seems that you have some unneeded calls to the grid api which when removed resolve your testing issue.

```ts
    private async loadGridData(): Promise<void> {
        try {
            console.warn('loading data')
            this.data.next(await this.getData())
            //this.agGrid?.api.refreshClientSideRowModel()
            //this.agGrid?.api.redrawRows()
        } catch (error) {
            console.error(error)
        } finally {
            this.removeLoadingOverlay()
        }
    }
```

I am not sure why you are calling refresh and redraw? The grid should automatically do this as you have provided row data via an observable. 

I also note that the grid is not actually rendered by the time the test runs due to the async nature of the tests. You may find the following doc page helpful. 

https://ag-grid.com/angular-data-grid/testing-async/
