### ISSUE TITLE
CellRenderer error "componentType is not a constructor" with Vue

### ISSUE THREAD

**Issue by itx-digital** [ag-grid/ag-grid#7267]
Hello,

I'm trying to upgrade to the latest version of ag-grid (I tried 30.1, 30.2 and 30.2.1), with ag-grid-vue.

I'm having issues with my existing cellRenderers, which worked fine with ag grid version 28.2.0.

First, I had the following errors:
_Cannot read properties of undefined (reading '_init')
TypeError: Cannot read properties of undefined (reading '_init')
at VueComponent (http://localhost:8080/js/chunk-vendors.js:215853:12)
    at Adapter.init (http://localhost:8080/js/chunk-vendors.js:47226:38)
    at push../node_modules/ag-grid-community/dist/ag-grid-community.auto.esm.js.UserComponentFactory.initComponent (http://localhost:8080/js/chunk-vendors.js:20954:26)
    at push../node_modules/ag-grid-community/dist/ag-grid-community.auto.esm.js.UserComponentFactory.newAgStackInstance (http://localhost:8080/js/chunk-vendors.js:20920:33)
    at Object.newAgStackInstance (http://localhost:8080/js/chunk-vendors.js:20858:60)
    at push../node_modules/ag-grid-community/dist/ag-grid-community.auto.esm.js.RowComp.showFullWidth (http://localhost:8080/js/chunk-vendors.js:32156:31)
    at Object.showFullWidth (http://localhost:8080/js/chunk-vendors.js:32121:66)
    at push../node_modules/ag-grid-community/dist/ag-grid-community.auto.esm.js.RowCtrl.setupFullWidth (http://localhost:8080/js/chunk-vendors.js:28103:21)
    at push../node_modules/ag-grid-community/dist/ag-grid-community.auto.esm.js.RowCtrl.initialiseRowComp (http://localhost:8080/js/chunk-vendors.js:28012:18)
    at push../node_modules/ag-grid-community/dist/ag-grid-community.auto.esm.js.RowCtrl.setComp (http://localhost:8080/js/chunk-vendors.js:27949:14)_

Then, I saw on the documentation that it might be because registering custom components by direct reference is no longer supported:
https://www.ag-grid.com/vue-data-grid/components/#registering-custom-components

**Therefore, I tried registering them through the :components attribute on my <ag-grid-vue> element and using them on my column definition such as cellRenderer: 'CountryCellRenderer'.
But this generates error "componentType is not a constructor".**

You can see a demo here:
https://stackblitz.com/edit/vitejs-vite-jv2jxj?file=src%2FApp.vue

Registering at the vue instance level works (uncomment related code in main.ts), but then, in my local project, it generates eslint's vue/no-unused-components errors such as "The "CountryCellRenderer" component has been registered but not used." as it doesn't detect usage , and I don't want to have to ignore them with // eslint-disable-next-line.

Can you please fix or provide a solution?

Thank you.

**Comment by AG-Zoheil** [comment]
Hi @itx-digital,

Thank you for submitting this on GitHub.

`script setup` is nothing something we had been supporting for Vue 2. In fact support for this was recently added to Vue 3. Are you able to provide a working example of your set up with AG Grid version 28.2.0?

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Comment by bhenderson-riparian** [comment]
I have this same issue. I was able to solve it by defining a components option in a second script block below the script setup block.

```
<script setup>
// define gridOptions, columnDefs
</script>
<script>
export default defineComponent({
  components: { CountryCellRenderer },
})
</script>
```

it would still be nice not to have to do this.
I personally miss registering by direct reference.
