### ISSUE TITLE
[31.0.3] AgGridReact - Error when unmounting grid when custom cellEditor is rendered and rangeSelection + fillHandle is enabled

### ISSUE THREAD

**Issue by pdeleastar** [ag-grid/ag-grid#7519]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

https://codesandbox.io/p/sandbox/ag-grid-modules-forked-zdh2yq

1. Focus any cell with a custom editor.
2. Click the "hide" button. 
3. The grid crashes with the following error:

```
Uncaught TypeError: Cannot read properties of null (reading 'get')
    at FillHandle.preConstructOnComponent (component.mjs:31:57)
    at eval (context.mjs:177:66)
    at Array.forEach (<anonymous>)
    at Context.callLifeCycleMethodsOnBean (context.mjs:177:20)
    at eval (context.mjs:162:48)
```

https://github.com/ag-grid/ag-grid/assets/13644905/fc2c4061-1b84-41d5-a25a-ee977558d1d3

**Comment by AG-Zoheil** [comment]
Hi @pdeleastar,

I've tried a different approach using one of the examples from our website and adjusting it and I am not getting an error - would this work for you?

https://plnkr.co/edit/9PONJUKCOrGTqR9t?open=index.jsx

Kind regards,
Zoheil

**Comment by pdeleastar** [comment]
Hi Zoheil, 

Thanks for the quick response. On the example you provided I do see the same error, I tested on both Chrome and Safari. Notice the "hide" button is not present after clicking, I see the error in the console also. 

Kind regards, 
Pierre

**Comment by AG-Zoheil** [comment]
Thanks @pdeleastar, I've cleared my cache and can also see it now. Checking this further.

**Comment by AG-Zoheil** [comment]
Hello @pdeleastar,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-10589**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
