### ISSUE TITLE
Filter example of Ag-Grid documentation does not actually work

### ISSUE THREAD

**Issue by mafalarz** [ag-grid/ag-grid#7722]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I purchased the enterprise edition, but at the moment cannot login to the zen desk. I sent an email to support, but not getting any help on that front either. 

In any case, I tried to follow the plunker example of this guide: https://www.ag-grid.com/angular-data-grid/filter-set-excel-mode/

I actually copied the code and pasted it in a brand new angular application, but it's not working at all. It's throwing error on browser. 

`main.ts:5  ERROR TypeError: Cannot read properties of null (reading 'firstCreatePass')
    at providersResolver (core.mjs:26716:15)
    at definition.providersResolver (core.mjs:26977:24)
    at initializeDirectives (core.mjs:11105:17)
    at resolveDirectives (core.mjs:11079:13)
    at elementStartFirstCreatePass (core.mjs:22243:5)
    at ɵɵelementStart (core.mjs:22279:9)
    at Module.ɵɵelement (core.mjs:22360:5)
    at AppComponent_Template (app.component.ts:13:14)
    at executeTemplate (core.mjs:10567:9)
    at renderView (core.mjs:11769:13)`

**Expected behavior**
That the provided example in the official documentation of Ag Grid actually work so we can use the feature we purchased.

**Please tell us about your environment:**
Windows 10
Visual Studio Code
Angular 17

* **AG Grid version:** X.X.X
Ag-Grid 31.10

* **Browser:**
Edge browser

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Angular 17 using Angular CLI

**Comment by AG-Zoheil** [comment]
Hi @mafalarz,

Thanks for getting in touch. As you can see in the documentation the example works.

We are unable to see what is missing on your side from what you've posted above. Have you managed to get your Zendesk access sorted as we can help more directly via that route?

Ideally, if you can provide a mini-project that shows the error we can be of more assistance.

Kind regards,
Zoheil
