### ISSUE TITLE
Cell renderer is not working in angular 17.2 + ag-grid 31.1.1

### ISSUE THREAD

**Issue by radek-stasta** [ag-grid/ag-grid#7736]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**

I have created medal-cell-renderer exactly copy paste as in https://www.ag-grid.com/angular-data-grid/component-cell-renderer/. I created simple grid:
```
protected colDefs: ColDef[] = [
  { field: 'gold', cellRenderer: MedalCellRenderer },
];
protected rowData = [ {'gold': 1}];
private _gridOptions: GridOptions = {
  columnDefs: this.colDefs,
  rowData: this.rowData,
};
...
...
const gridDiv = document.querySelector<HTMLElement>('#ag-grid');
if (gridDiv) {
  createGrid(gridDiv, this._gridOptions);
}
```
And when I try to display it, I am getting error:

> ERROR TypeError: Class constructor _MedalCellRenderer cannot be invoked without 'new'
>     at Adapter2.init (ag-grid-community.auto.esm.js:49819:38)
>     at UserComponentFactory2.initComponent (ag-grid-community.auto.esm.js:20902:26)
>     at UserComponentFactory2.newAgStackInstance (ag-grid-community.auto.esm.js:20872:33)
>     at Object.newAgStackInstance (ag-grid-community.auto.esm.js:20810:60)
>     at createCellRendererFunc (ag-grid-community.auto.esm.js:33072:48)
>     at AnimationFrameService2.executeFrame (ag-grid-community.auto.esm.js:39142:21)
>     at timer (zone.js:2402:41)
>     at _ZoneDelegate.invokeTask (zone.js:403:31)
>     at core.mjs:15293:55
>     at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:15293:36)

Am I doing something wrong? Or is it a bug? Something I can do to make it work?

**Expected behavior**
Expected to work as in example code on your site, since it is basically 1:1 to what you have

**Please tell us about your environment:**
archlinux, Webstorm, npm, nginx but it is not relevant I think

* **AG Grid version:** 31.1.1

* **Browser:**
'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'

* **Language:** 
Angular 17, typescript
dependencies:
```
"dependencies": {
    "@angular/animations": "^17.2.0",
    "@angular/common": "^17.2.0",
    "@angular/compiler": "^17.2.0",
    "@angular/core": "^17.2.0",
    "@angular/forms": "^17.2.0",
    "@angular/platform-browser": "^17.2.0",
    "@angular/platform-browser-dynamic": "^17.2.0",
    "@angular/router": "^17.2.0",
    "ag-grid-angular": "^31.1.1",
    "bootstrap": "^5.3.3",
    "bootstrap-icons": "^1.11.3",
    "ngx-cookie-service": "^17.1.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^17.2.3",
    "@angular-eslint/builder": "17.2.1",
    "@angular-eslint/eslint-plugin": "17.2.1",
    "@angular-eslint/eslint-plugin-template": "17.2.1",
    "@angular-eslint/schematics": "17.2.1",
    "@angular-eslint/template-parser": "17.2.1",
    "@angular/cli": "^17.2.3",
    "@angular/compiler-cli": "^17.2.0",
    "@types/jasmine": "~5.1.0",
    "@typescript-eslint/eslint-plugin": "6.19.0",
    "@typescript-eslint/parser": "6.19.0",
    "eslint": "^8.56.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-prettier": "^5.1.3",
    "jasmine-core": "~5.1.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "ng-packagr": "^17.2.0",
    "prettier": "^3.2.5",
    "prettier-eslint": "^16.3.0",
    "typescript": "~5.3.2"
  }
```

**Comment by Alijavedofficial** [comment]
Make sure that your MedalCellRenderer class is correctly defined as an Angular component and implements the ICellRendererAngularComp interface. This interface requires the implementation of agInit and refresh methods, as shown in the AG Grid documentation .

**Comment by radek-stasta** [comment]
It is a copy/paste from ag-grid example:
```
import { Component } from '@angular/core';
import { ICellRendererAngularComp } from 'ag-grid-angular';
import { ICellRendererParams } from 'ag-grid-community';

@Component({
  standalone: true,
  template: `<span>{{ this.displayValue }}</span>`,
})
export class MedalCellRenderer implements ICellRendererAngularComp {
  public displayValue!: string;

  agInit(params: ICellRendererParams<IOlympicData, number>): void {
    this.displayValue = new Array(params.value!).fill('#').join('');
  }

  refresh(params: ICellRendererParams) {
    return false;
  }
}

export interface IOlympicData {
  athlete: string;
  age: number;
  country: string;
  year: number;
  date: string;
  sport: string;
  gold: number;
  silver: number;
  bronze: number;
  total: number;
}
```

**Comment by Alijavedofficial** [comment]
Make sure that your MedalCellRenderer component is correctly registered in your Angular module's declarations. This is crucial for Angular to recognize and properly instantiate the component.

**Comment by radek-stasta** [comment]
There are no modules by default in Angular 17 onwards. Standalone is new default and there is only app.config.ts, that looks like this:

```
import { ApplicationConfig } from '@angular/core';
import { provideRouter } from '@angular/router';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [provideRouter(routes)],
};
```

**Comment by StephenCooper** [comment]
By using the JavaScript creategrid function you are not using the Angular version of AG Grid. 

```
if (gridDiv) {
  createGrid(gridDiv, this._gridOptions);
}
```

Instead please use the `<ag-grid-angular>` selector in your html template

**Comment by radek-stasta** [comment]
> By using the JavaScript creategrid function you are not using the Angular version of AG Grid.
> 
> ```
> if (gridDiv) {
>   createGrid(gridDiv, this._gridOptions);
> }
> ```
> 
> Instead please use the `<ag-grid-angular>` selector in your html template

You are the hero. That indeed did the trick and it is now working. Thanks a lot for your help!

**Comment by jzs11** [comment]
Hi team, this is still an issue, the work around is ok, but best to keep using ag-grid-angular.
