### ISSUE TITLE
[Regression 31.2.0 -> 31.2.1] Cannot import the minified version of styles

### ISSUE THREAD

**Issue by ghostd** [ag-grid/ag-grid#7836]
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
After upgrading to 32.2.1 we get this error while building our application (we use `vite`to bundle the application):
```
Error: [commonjs--resolver] Missing "./styles/ag-grid.min.css" specifier in "ag-grid-community" package
```

**Expected behavior**
A successful build

* **AG Grid version:** 31.2.1

After a bit digging we found a difference in the "exports" part of the package.json

In 31.2.0:
```json
  "exports": {
    ".": {
      "import": "./dist/package/main.esm.mjs",
      "require": "./dist/package/main.cjs.js",
      "types": "./dist/types/main.d.ts",
      "default": "./dist/package/main.cjs.js"
    },
    "./styles/*": "./styles/*"
  },
```

In 31.2.1:
```json
  "exports": {
    ".": {
      "import": "./dist/package/main.esm.mjs",
      "require": "./dist/package/main.cjs.js",
      "types": "./dist/types/main.d.ts",
      "default": "./dist/package/main.cjs.js"
    },
    "./styles/ag-grid.css": "./styles/ag-grid.css",
    "./styles/ag-theme-alpine.css": "./styles/ag-theme-alpine.css",
    "./styles/ag-theme-balham.css": "./styles/ag-theme-balham.css",
    "./styles/ag-theme-material.css": "./styles/ag-theme-material.css",
    "./styles/ag-theme-quartz.css": "./styles/ag-theme-quartz.css",
    "./styles": "./styles/_index.scss"
  },
```

The last version does not expose the minified version anymore (but the files are published in the package)

**Comment by tienipia** [comment]
Vite 5.2.8 (with ag-grid version 31.2.1) throw me error.

I think this must be related issue.

Of course, ag-grid version 31.2.0 was fine.
```
8:30:47 PM [vite] Internal server error: [postcss] Missing "./styles/ag-grid.min.css" specifier in "ag-grid-community" package
  Plugin: vite:css
  File: /home/tienipia/Repository/saeroun-gw-web/style/index.css?direct:undefined:NaN
      at e (file:///home/tienipia/Repository/saeroun-gw-web/node_modules/.store/vite-virtual-84f10bb258/package/dist/node/chunks/dep-whKeNLxG.js:47635:25)
      at n (file:///home/tienipia/Repository/saeroun-gw-web/node_modules/.store/vite-virtual-84f10bb258/package/dist/node/chunks/dep-whKeNLxG.js:47635:627)
      at o (file:///home/tienipia/Repository/saeroun-gw-web/node_modules/.store/vite-virtual-84f10bb258/package/dist/node/chunks/dep-whKeNLxG.js:47635:1297)
      at resolveExportsOrImports (file:///home/tienipia/Repository/saeroun-gw-web/node_modules/.store/vite-virtual-84f10bb258/package/dist/node/chunks/dep-whKeNLxG.js:48325:20)
      at resolveDeepImport (file:///home/tienipia/Repository/saeroun-gw-web/node_modules/.store/vite-virtual-84f10bb258/package/dist/node/chunks/dep-whKeNLxG.js:48344:31)
      at tryNodeResolve (file:///home/tienipia/Repository/saeroun-gw-web/node_modules/.store/vite-virtual-84f10bb258/package/dist/node/chunks/dep-whKeNLxG.js:48069:20)
      at Context.resolveId (file:///home/tienipia/Repository/saeroun-gw-web/node_modules/.store/vite-virtual-84f10bb258/package/dist/node/chunks/dep-whKeNLxG.js:47819:28)
      at Object.resolveId (file:///home/tienipia/Repository/saeroun-gw-web/node_modules/.store/vite-virtual-84f10bb258/package/dist/node/chunks/dep-whKeNLxG.js:51096:64)
      at async Object.<anonymous> (file:///home/tienipia/Repository/saeroun-gw-web/node_modules/.store/vite-virtual-84f10bb258/package/dist/node/chunks/dep-whKeNLxG.js:68287:21)
      at async Object.resolve (file:///home/tienipia/Repository/saeroun-gw-web/node_modules/.store/vite-virtual-84f10bb258/package/dist/node/chunks/dep-whKeNLxG.js:32181:34)
```

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-11313**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil
