### ISSUE TITLE
cellRenderer component and update rowData, throw error

### ISSUE THREAD

**Issue by MurphyHou123** [ag-grid/ag-grid#7912]
when using cellRenderer component, and update rowData (eg. by pagination), error happened:
Uncaught (in promise) Error: AG Grid: cannot get grid to draw rows when it is in the middle of drawing rows. Your code probably called a grid API method while the grid was in the render stage. To overcome this, put the API call into a timeout, e.g. instead of api.redrawRows(), call setTimeout(function() { api.redrawRows(); }, 0). To see what part of your code that caused the refresh check this stacktrace.
    at RowRenderer.getLockOnRefresh (main.esm.mjs:35062:13)
    at RowRenderer.redrawAfterModelUpdate (main.esm.mjs:35017:10)
    at RowRenderer.onPageLoaded (main.esm.mjs:34897:10)
    at main.esm.mjs:1017:99
    at VanillaFrameworkOverrides.wrapIncoming (main.esm.mjs:40789:39)
    at main.esm.mjs:1017:80
    at main.esm.mjs:1021:9
    at Set.forEach (<anonymous>)
    at processEventListeners (main.esm.mjs:1013:82)
    at EventService.dispatchToListeners (main.esm.mjs:1027:7)

**Comment by MurphyHou123** [comment]
when i remove cellRenderer, then no issue anymore. It's easy to reproduce. So i won't provide more evidences.

**Comment by MurphyHou123** [comment]
I resolve it by gridApi.value.redrawRows + gridApi.value.setGridOption. This should be resolved by one method gridApi.value.setGridOption only but not two method. maybe this can assess if any cellRenderer then deal with the issue internally.

**Comment by MurphyHou123** [comment]
there is still problem when drag column or other action trigger update column. the same error caused by cellRenderer. Please confirm.

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil
