### ISSUE TITLE
"RangeError: Invalid string length" when exporting as CSV with > 1M of rows 

### ISSUE THREAD

**Issue by bartekgruszka** [ag-grid/ag-grid#8070]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

I'm getting the following error when trying to export > 1M of rows x 45 columns

```
Uncaught RangeError: Invalid string length
    at t.onNewBodyRowColumn (ag-grid-enterprise.cjs.js:5983:29)
    at eval (ag-grid-enterprise.cjs.js:6191:28)
    at Array.forEach (<anonymous>)
    at t.processRow (ag-grid-enterprise.cjs.js:6190:25)
    at r.recursivelyWalkNodesAndCallback (ag-grid-community.cjs.js:44781:13)
    at r.forEachNodeAfterFilterAndSort (ag-grid-community.cjs.js:44765:14)
    at eval (ag-grid-enterprise.cjs.js:6300:34)
    at eval (ag-grid-community.cjs.js:912:79)
    at Array.reduce (<anonymous>)
    at eval (ag-grid-community.cjs.js:912:40)
    at t.serialize (ag-grid-enterprise.cjs.js:6155:16)
    at e.getMergedParamsAndData (ag-grid-enterprise.cjs.js:5753:46)
    at t.export (ag-grid-enterprise.cjs.js:6057:23)
    at t.exportDataAsCsv (ag-grid-enterprise.cjs.js:6066:21)
    at e.exportDataAsCsv (ag-grid-community.cjs.js:30958:29)

```

Is there anything we can do about it?

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by bartekgruszka** [comment]
@AG-Zoheil I’m sorry for the late reply, here's a plunker that reproduces the issue: https://plnkr.co/edit/UhmSTAQAEgJI0ykz?preview

Just click the "Export to CSV" button and you'll get:

In Chrome:
```
ag-grid-community.min.js:8 Uncaught RangeError: Invalid string length
    at t.onNewBodyRowColumn (ag-grid-community.min.js:8:594120)
    at ag-grid-community.min.js:8:599386
    at Array.forEach (<anonymous>)
    at t.processRow (ag-grid-community.min.js:8:599361)
    at t.recursivelyWalkNodesAndCallback (ag-grid-community.min.js:8:568835)
    at t.forEachNodeAfterFilterAndSort (ag-grid-community.min.js:8:568512)
    at ag-grid-community.min.js:8:601715
    at ag-grid-community.min.js:8:96036
    at Array.reduce (<anonymous>)
    at ag-grid-community.min.js:8:96007
```

In FireFox:

```
Uncaught InternalError: allocation size overflow
    onNewBodyRowColumn https://cdnjs.cloudflare.com/ajax/libs/ag-grid/25.3.0/ag-grid-community.min.js:8
    processRow https://cdnjs.cloudflare.com/ajax/libs/ag-grid/25.3.0/ag-grid-community.min.js:8
    processRow https://cdnjs.cloudflare.com/ajax/libs/ag-grid/25.3.0/ag-grid-community.min.js:8
    recursivelyWalkNodesAndCallback https://cdnjs.cloudflare.com/ajax/libs/ag-grid/25.3.0/ag-grid-community.min.js:8
    forEachNodeAfterFilterAndSort https://cdnjs.cloudflare.com/ajax/libs/ag-grid/25.3.0/ag-grid-community.min.js:8
    f https://cdnjs.cloudflare.com/ajax/libs/ag-grid/25.3.0/ag-grid-community.min.js:8
    b https://cdnjs.cloudflare.com/ajax/libs/ag-grid/25.3.0/ag-grid-community.min.js:8
    b https://cdnjs.cloudflare.com/ajax/libs/ag-grid/25.3.0/ag-grid-community.min.js:8
    serialize https://cdnjs.cloudflare.com/ajax/libs/ag-grid/25.3.0/ag-grid-community.min.js:8
    getMergedParamsAndData https://cdnjs.cloudflare.com/ajax/libs/ag-grid/25.3.0/ag-grid-community.min.js:8
    export https://cdnjs.cloudflare.com/ajax/libs/ag-grid/25.3.0/ag-grid-community.min.js:8
    exportDataAsCsv https://cdnjs.cloudflare.com/ajax/libs/ag-grid/25.3.0/ag-grid-community.min.js:8
    exportDataAsCsv https://cdnjs.cloudflare.com/ajax/libs/ag-grid/25.3.0/ag-grid-community.min.js:8
    onBtnExport https://run.plnkr.co/preview/cly5ngf8i0006286vcp9jp688/:63
    onclick https://run.plnkr.co/preview/cly5ngf8i0006286vcp9jp688/:1
[ag-grid-community.min.js:8:594120](https://cdnjs.cloudflare.com/ajax/libs/ag-grid/25.3.0/ag-grid-community.min.js)

​
```

**Comment by AG-Zoheil** [comment]
Hi @bartekgruszka,

Thanks for getting back.

It looks like you are hitting the browser defined limit. I'm afraid it is not possible for AG Grid to work around this. You would have to break down your data to acceptable levels for the browser.
